### PR TITLE
Feature/twisted hasen

### PR DESCRIPTION
**Pull request by sunwayihep**
Add the multigrid support for symmetric preconditioned twisted-Hasenbusch operator 
M_s = 1 - kappa^2 A^{-1}_oo D_oe A^{-1}_ee D_eo + i \mu * \gamma_5 * A_oo. 
Currently only support the symmetric even-odd preconditioning for multigrid.

### CODE REVIEW

**Comment by maddyscientist** [comment]
@sunwayihep not sure if you can see the Jenkins build failures, but I can see that your pull is generating some build errors.  For pull requests, we treat warnings as errors.  Can you fix these before we merge in?

```
/scratch/jenkins/.jenkins/jobs/ubuntu1804_gnu7_clang6_openmpi3_cmake3122_cuda100/workspace/GPUARCH/sm_70/include/dirac_quda.h:459:18: error: 'M' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]
    virtual void M(ColorSpinorField &out, const ColorSpinorField &in) const;
                 ^
/scratch/jenkins/.jenkins/jobs/ubuntu1804_gnu7_clang6_openmpi3_cmake3122_cuda100/workspace/GPUARCH/sm_70/include/dirac_quda.h:360:18: note: overridden virtual function is here
    virtual void M(ColorSpinorField &out, const ColorSpinorField &in) const;
                 ^
/scratch/jenkins/.jenkins/jobs/ubuntu1804_gnu7_clang6_openmpi3_cmake3122_cuda100/workspace/GPUARCH/sm_70/include/dirac_quda.h:460:18: error: 'MdagM' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]
    virtual void MdagM(ColorSpinorField &out, const ColorSpinorField &in) const;
                 ^
/scratch/jenkins/.jenkins/jobs/ubuntu1804_gnu7_clang6_openmpi3_cmake3122_cuda100/workspace/GPUARCH/sm_70/include/dirac_quda.h:361:18: note: overridden virtual function is here
    virtual void MdagM(ColorSpinorField &out, const ColorSpinorField &in) const;
                 ^
/scratch/jenkins/.jenkins/jobs/ubuntu1804_gnu7_clang6_openmpi3_cmake3122_cuda100/workspace/GPUARCH/sm_70/include/dirac_quda.h:471:10: error: 'createCoarseOp' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]
    void createCoarseOp(GaugeField &Y, GaugeField &X, const Transfer &T, double kappa, double mass = 0., double mu = 0.,
         ^
/scratch/jenkins/.jenkins/jobs/ubuntu1804_gnu7_clang6_openmpi3_cmake3122_cuda100/workspace/GPUARCH/sm_70/include/dirac_quda.h:378:10: note: overridden virtual function is here
    void createCoarseOp(GaugeField &Y, GaugeField &X, const Transfer &T,
         ^
/scratch/jenkins/.jenkins/jobs/ubuntu1804_gnu7_clang6_openmpi3_cmake3122_cuda100/workspace/GPUARCH/sm_70/include/dirac_quda.h:509:11: error: 'M' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]
     void M(ColorSpinorField &out, const ColorSpinorField &in) const;
          ^
/scratch/jenkins/.jenkins/jobs/ubuntu1804_gnu7_clang6_openmpi3_cmake3122_cuda100/workspace/GPUARCH/sm_70/include/dirac_quda.h:406:10: note: overridden virtual function is here
    void M(ColorSpinorField &out, const ColorSpinorField &in) const;
         ^
/scratch/jenkins/.jenkins/jobs/ubuntu1804_gnu7_clang6_openmpi3_cmake3122_cuda100/workspace/GPUARCH/sm_70/include/dirac_quda.h:512:11: error: 'MdagM' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]
     void MdagM(ColorSpinorField &out, const ColorSpinorField &in) const;
          ^
/scratch/jenkins/.jenkins/jobs/ubuntu1804_gnu7_clang6_openmpi3_cmake3122_cuda100/workspace/GPUARCH/sm_70/include/dirac_quda.h:409:10: note: overridden virtual function is here
    void MdagM(ColorSpinorField &out, const ColorSpinorField &in) const;
         ^
/scratch/jenkins/.jenkins/jobs/ubuntu1804_gnu7_clang6_openmpi3_cmake3122_cuda100/workspace/GPUARCH/sm_70/include/dirac_quda.h:526:11: error: 'createCoarseOp' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]
     void createCoarseOp(GaugeField &Y, GaugeField &X, const Transfer &T,
          ^
/scratch/jenkins/.jenkins/jobs/ubuntu1804_gnu7_clang6_openmpi3_cmake3122_cuda100/workspace/GPUARCH/sm_70/include/dirac_quda.h:429:10: note: overridden virtual function is here
    void createCoarseOp(GaugeField &Y, GaugeField &X, const Transfer &T,
```

**Comment by sunwayihep** [comment]
@maddyscientist It seems the `-Werror` flag of clang compiler will include the `-Winconsistent-missing-override` by default, which warn the mixing use of `override` keyword, so I just remove the `override`.
I'm not sure why the other failed, can't see the details of the failures...

**Comment by maddyscientist** [comment]
@sunwayihep the remaining build errors are just complaints about failing builds with C++11.  That's ok, and expected.  QUDA has switched to C++14, but we've kept the C++11 builds on the Jenkins server since the `release/1.0.x` branch still need this.

I will merge your branch now into the local branch `feature/twisted-hasen`.  My plan is then to apply a couple of changes to this, do some testing, and then we'll open up a new pull to get this into develop.  Sound ok?

**Comment by maddyscientist** [comment]
BTW, to see the build errors, you need to click on the red cross next to open up the list of failing builds (though not if it's already open), and then click on `Details` from a failing build.  This should take you to the Jenkins server, and finally then clicking on `Console Output` will show you the log from the build.

**Comment by sunwayihep** [comment]
@maddyscientist sounds great, thanks.

**Pull request merged**
