### PR TITLE
Feature/rdma

### LINKED ISSUE #580: Implement MdagM operator for DslashCoarse
This is missing and prevents the use of CG and related solvers on the coarse grids.  PErhaps will be troublesome on the preconditioned operator, need to think about this.

### LINKED ISSUE #611: Possible bug in twisted-mass nondeg for half precision
@alexstrel can you check line 961 of tm_core.h?

float a = param.a_f
float b = param.b_f
float c = param.b_f

I guess the third sould be

float c = param.c_f

Am I missing something?

### PR DESCRIPTION
**Pull request by maddyscientist**
This pull request is a significant improvement to both multigrid and the multi-GPU / multi-node performance of QUDA
* Added full support for GPU Direct RDMA and CUDA-aware MPI for all dslash types (enabled by setting `QUDA_ENABLE_GDR`).  This includes a dramatic cleanup of the communication handling, making it more robust and maintainable.
* Dslash and DslashCoarse policy types can now be set using environment variables for targeted testing and benchmarking (see [here](https://github.com/lattice/quda/wiki/Multi-GPU-Support#dslash-policy-tuning).
* Dslash components can be benchmarked in isolation for better understanding of bottlenecks (see [here](https://github.com/lattice/quda/wiki/Multi-GPU-Support#dslash-component-benchmarking) )
* Removed the need to use MAGMA with multigrid - use CUBLAS instead for batched matrix inversion
* Added new interface `updateMultigridQuda` for use in HMC to allow for updating the MG null-vector space.
* Added accompanying test multigrid_evolve_test that uses the heatbath overrelaxation algorithm to demonstrate this.
* Added atomic support to the fine-grained accessors 
* Offloaded all of the coarse-link construction onto the GPU.  This provides a significant speedup of the multigrid set up.
* Improved compile time where possible of multigrid operator through minimizing the templates instantiated
* Fix performance regression in coarse dslash operator 
* Adds support for the Hermitian conjugate coarse Dslash operator (closes #580)
* Includes @sbacchio initial work on improving twisted-mass and twisted-clover multigrid support (#590, #581)
* Completely reworked multi-blas and multi-reduce kernels that provides better recursion, more robust multi reductions and the template explosion is now controlled with the `QUDA_MAX_MULTI_BLAS_N` cmake build parameter
* QUDA now works on Fermi again
* Closes #611, #609.
* Multiple minor bug fixes and cleanup

### CODE REVIEW

**Comment by mathiaswagner** [comment]
Looks like Fermi is becoming harder and harder to support:

```
FAILED: cd /scratch/jenkins/.jenkins/jobs/QUDAcmake/workspace/CUDAVERSION/8.0/GPUARCH/sm_20/strict/lib/CMakeFiles/quda.dir && /scratch/jenkins/cmake-3.5.2-Linux-x86_64/bin/cmake -E make_directory /scratch/jenkins/.jenkins/jobs/QUDAcmake/workspace/CUDAVERSION/8.0/GPUARCH/sm_20/strict/lib/CMakeFiles/quda.dir//. && /scratch/jenkins/cmake-3.5.2-Linux-x86_64/bin/cmake -D verbose:BOOL=OFF -D build_configuration:STRING=STRICT -D generated_file:STRING=/scratch/jenkins/.jenkins/jobs/QUDAcmake/workspace/CUDAVERSION/8.0/GPUARCH/sm_20/strict/lib/CMakeFiles/quda.dir//./quda_generated_multi_reduce_quda.cu.o -D generated_cubin_file:STRING=/scratch/jenkins/.jenkins/jobs/QUDAcmake/workspace/CUDAVERSION/8.0/GPUARCH/sm_20/strict/lib/CMakeFiles/quda.dir//./quda_generated_multi_reduce_quda.cu.o.cubin.txt -P /scratch/jenkins/.jenkins/jobs/QUDAcmake/workspace/CUDAVERSION/8.0/GPUARCH/sm_20/strict/lib/CMakeFiles/quda.dir//quda_generated_multi_reduce_quda.cu.o.cmake
ptxas error   : Entry function '_ZN4quda4blas6reduce17multiReduceKernelILi512E7double26float2Li1ELi4ENS1_5multi13SpinorTextureIS4_S4_Li1ELi0EEENS5_6SpinorIS4_S4_Li1ELi0ELi1EEENS6_IS4_S4_Li1ELi2EEENS8_IS4_S4_Li1ELi0ELi3EEENS0_4CdotILi4ES3_S4_S4_EEEEvNS1_14MultiReduceArgIXT3_ET0_T4_T5_T6_T7_T8_EE' uses too much shared data (0xc750 bytes, 0xc000 max)
ptxas error   : Entry function '_ZN4quda4blas6reduce17multiReduceKernelILi512E7double2S3_Li1ELi4ENS1_5multi13SpinorTextureIS3_S3_Li1ELi0EEENS4_6SpinorIS3_S3_Li1ELi0ELi1EEENS5_IS3_S3_Li1ELi2EEENS7_IS3_S3_Li1ELi0ELi3EEENS0_4CdotILi4ES3_S3_S3_EEEEvNS1_14MultiReduceArgIXT3_ET0_T4_T5_T6_T7_T8_EE' uses too much shared data (0xc750 bytes, 0xc000 max)
ptxas error   : Entry function '_ZN4quda4blas6reduce17multiReduceKernelILi512E7double26float2Li3ELi4ENS1_5multi13SpinorTextureIS4_6short2Li3ELi0EEENS5_6SpinorIS4_S7_Li3ELi0ELi1EEENS6_IS4_S7_Li3ELi2EEENS9_IS4_S7_Li3ELi0ELi3EEENS0_4CdotILi4ES3_S4_S4_EEEEvNS1_14MultiReduceArgIXT3_ET0_T4_T5_T6_T7_T8_EE' uses too much shared data (0xc750 bytes, 0xc000 max)
ptxas error   : Entry function '_ZN4quda4blas6reduce17multiReduceKernelILi512E7double26float4Li1ELi4ENS1_5multi13SpinorTextureIS4_S4_Li1ELi0EEENS5_6SpinorIS4_S4_Li1ELi0ELi1EEENS6_IS4_S4_Li1ELi2EEENS8_IS4_S4_Li1ELi0ELi3EEENS0_4CdotILi4ES3_6float2S4_EEEEvNS1_14MultiReduceArgIXT3_ET0_T4_T5_T6_T7_T8_EE' uses too much shared data (0xc750 bytes, 0xc000 max)
ptxas error   : Entry function '_ZN4quda4blas6reduce17multiReduceKernelILi512E7double26float4Li6ELi4ENS1_5multi13SpinorTextureIS4_6short4Li6ELi0EEENS5_6SpinorIS4_S7_Li6ELi0ELi1EEENS6_IS4_S7_Li6ELi2EEENS9_IS4_S7_Li6ELi0ELi3EEENS0_4CdotILi4ES3_6float2S4_EEEEvNS1_14MultiReduceArgIXT3_ET0_T4_T5_T6_T7_T8_EE' uses too much shared data (0xc750 bytes, 0xc000 max)
CMake Error at quda_generated_multi_reduce_quda.cu.o.cmake:268 (message):
  Error generating file
  /scratch/jenkins/.jenkins/jobs/QUDAcmake/workspace/CUDAVERSION/8.0/GPUARCH/sm_20/strict/lib/CMakeFiles/quda.dir//./quda_generated_multi_reduce_quda.cu.o
```

**Comment by alexstrel** [comment]
Also, deflation stuff has some conflicts
/home/astrel/Work/quda-deflation-rdma-check/lib/inv_eigcg_quda.cpp:130:12: error: no matching function for call to 'cDotProduct'
           blas::cDotProduct(&s[offset], w_, v_);//<i, b>
           ^~~~~~~~~~~~~~~~~
/home/astrel/Work/quda-deflation-rdma-check/include/blas_quda.h:313:10: note: candidate function not viable: no known conversion from 'std::vector<cudaColorSpinorField *>' to 'std::vector<ColorSpinorField *> &' for 2nd argument
    void cDotProduct(Complex* result, std::vector<ColorSpinorField*>& a, std::vector<ColorSpinorField*>& b);
         ^
/home/astrel/Work/quda-deflation-rdma-check/include/blas_quda.h:65:13: note: candidate function not viable: requires 2 arguments, but 3 were provided
    Complex cDotProduct(ColorSpinorField &, ColorSpinorField &);

**Comment by maddyscientist** [comment]
@alexstrel This problem appears to be because you're using `cudaColorSpinorField` not `ColorSpinorField`, which is required for all the blas functions.  Can you update the deflated solvers appropriately?

**Comment by alexstrel** [comment]
@maddyscientist yes, I noted this. I'll update once finish tests on Minsky later today

**Comment by alexstrel** [comment]
Deflation solvers do not work in the rdma branch, I got memory corruption errors both on Minsky and Titan X desktop. In the eigCG solver this happens inside RR block. Did not check fgmresdr, though.

**Comment by cpviolator** [comment]
I've compiled this branch on Piz-Daint, but `multigrid_invert_test` is failing at the mg set-up. Here are my environment details:

`cudatoolkit/8.0.54_2.2.8_ga620558-2.1`
`cray-mpich/7.5.0`
with Cray wrappers
`/opt/cray/pe/craype/2.5.8/bin/cc`
and 
`/opt/cray/pe/craype/2.5.8/bin/CC`
for `gcc` and `g++` respectively (`g++ (GCC) 5.3.0 20151204 (Cray Inc.)`

I have in by bashrc script and sbatch submission scripts the following recommended environment variables:
`export CUDA_MAX_DEVICE_CONNECTIONS=1`
`export MPICH_RDMA_ENABLED_CUDA=1`
`export MPICH_NEMESIS_ASYNC_PROGRESS=1`
`export QUDA_ENABLE_GDR=1`
during compilation and job submission. The error is giving some info:
`PE 0: MPICH Warning: Application not linked with Cuda library. Disabling MPICH_RDMA_ENABLED_CUDA.`
`Message buffer is a device (gpu) buffer: set environment variable MPICH_RDMA_ENABLED_CUDA to enabled`
So it disables the `MPICH_RDMA_ENABLED_CUDA` variable before launching the job, which then fails... because it should be enabled.

Is this a Piz-Daint issue I should submit a ticket for, or am I missing an important step?

**Comment by maddyscientist** [comment]
@cpviolator that does look like a weird message.  So is the program running and giving an actual QUDA error?

How many processes, local volume etc.  Can you give me a command for multigrid_invert_test that I can try to reproduce?

**Comment by cpviolator** [comment]
Sure thing, here's the run command:

Run command is:

srun -n 8 --ntasks-per-node=1 -c 12 ./multigrid_invert_test --dslash-type
twisted-clover --prec double --prec-sloppy single --prec-precondition
single --recon 18 --recon-sloppy 18 --recon-precondition 18 --xdim 32
--ydim 16 --zdim 16 --tdim 32 --xgridsize 1 --ygridsize 2 --zgridsize 2
--tgridsize 2 --mg-levels 2 --mg-block-size 0 4 4 8 8 --mg-nu-pre 0
--mg-nu-post 4 --mg-setup-tol 5e-7 --mg-setup-inv 0 cg --mg-mu-factor 0
16.0 --mg-verbosity 0 summarize

**Comment by cpviolator** [comment]
The full error message is:

PE 0: MPICH Warning: Application not linked with Cuda library. Disabling
MPICH_RDMA_ENABLED_CUDA.

Message buffer is a device (gpu) buffer: set environment variable
MPICH_RDMA_ENABLED_CUDA to enabled

5: MPICH2 Error: Failed to register memory address 0x10223bb0000 with
length of 0x30000 (196608) bytes.

5: Unable to register memory at the requested address. This may indicate an
application bug. See process virtual memory mappings below:

5: 00400000-0cba1000 r-xp 00000000 00:38 51854792
/users/howarth/MG_Bench/multigrid_invert_test

5: 0cda1000-0cda4000 r-xp 0c7a1000 00:38 51854792
/users/howarth/MG_Bench/multigrid_invert_test

5: 0cda4000-0cda5000 rwxp 0c7a4000 00:38 51854792
/users/howarth/MG_Bench/multigrid_invert_test

5: 0cda5000-4d796000 rwxp 00000000 00:00 0
[heap]

5: 200000000-200200000 rwxs cd0f32000 00:06 84086
/dev/nvidiactl

5: 200200000-200400000 ---p 00000000 00:00 0

5: 200400000-200404000 rwxs cdc409000 00:06 84086
/dev/nvidiactl

5: 200404000-200600000 ---p 00000000 00:00 0

5: 200600000-200a00000 rwxs f53b81000 00:06 84086
/dev/nvidiactl

5: 200a00000-201600000 ---p 00000000 00:00 0

5: 201600000-201604000 rwxs f4ac9a000 00:06 84086
/dev/nvidiactl

5: 201604000-201800000 ---p 00000000 00:00 0

5: 201800000-201c00000 rwxs f4c5e8000 00:06 84086
/dev/nvidiactl

5: 201c00000-202800000 ---p 00000000 00:00 0

5: 202800000-202804000 rwxs f4939a000 00:06 84086
/dev/nvidiactl

5: 202804000-202a00000 ---p 00000000 00:00 0

5: 202a00000-202e00000 rwxs f52d3c000 00:06 84086
/dev/nvidiactl

5: 202e00000-203a00000 ---p 00000000 00:00 0

5: 203a00000-203a04000 rwxs f5acb3000 00:06 84086
/dev/nvidiactl

5: 203a04000-203c00000 ---p 00000000 00:00 0

5: 203c00000-204000000 rwxs fbac0d000 00:06 84086
/dev/nvidiactl

5: 204000000-204c00000 ---p 00000000 00:00 0

5: 204c00000-204c04000 rwxs f5715d000 00:06 84086
/dev/nvidiactl

5: 204c04000-204e00000 ---p 00000000 00:00 0

5: 204e00000-205200000 rwxs 750898000 00:06 84086
/dev/nvidiactl

5: 205200000-205e00000 ---p 00000000 00:00 0

5: 205e00000-205e04000 rwxs f4eb3d000 00:06 84086                Message
buffer is a device (gpu) buffer: set environment variable
MPICH_RDMA_ENABLED_CUDA to\

 enabled


which then just repeats for different ranks.

**Comment by cpviolator** [comment]
The full QUDA output is here:

Enabling GPU-Direct RDMA access
running the following test:
prec    sloppy_prec    link_recon  sloppy_link_recon S_dimension T_dimension Ls_dimension
double   single             18            18            32/16/16          32         16
MG parameters
 - number of levels 2
 - level 1 number of null-space vectors 0
 - number of pre-smoother applications 0
 - number of post-smoother applications 4
Grid partition info:     X  Y  Z  T
                         0  1  1  1
QUDA 0.9.0 (git v0.8.0-1916-g9feb71c-dirty-sm_60)
Found device 0: Tesla P100-PCIE-16GB
Using device 0: Tesla P100-PCIE-16GB
WARNING: Data reordering done on GPU (set with QUDA_REORDER_LOCATION=GPU/CPU)
WARNING: Using device memory pool allocator
WARNING: Using pinned memory pool allocator
WARNING: Cache file not found.  All kernels will be re-tuned (if tuning is enabled).
Tuned block=(128,2,1), shared=0,  giving 0.00 Gflop/s, 112.00 GB/s for N4quda12CloverInvertIdNS_6clover11FloatNOrderIdLi72ELi2EEEEE with stride=131072,prec=8,trlog=false,twist=true
Tuned block=(160,1,1), shared=16385,  giving 0.00 Gflop/s, 545.92 GB/s for N4quda10CopyCloverIfdLi72ENS_6clover11FloatNOrderIfLi72ELi4EEENS2_IdLi72ELi2EEEEE with out_stride=131072,in_stride=131072
Tuned block=(32,1,1), shared=16385,  giving 0.00 Gflop/s, 265.38 GB/s for N4quda10CopyCloverIddLi72ENS_6clover8QDPOrderIdLi72EEENS1_11FloatNOrderIdLi72ELi2EEEEE with out_stride=131072,in_stride=131072
Creating vector of null space fields of length 24
MG level 1 (GPU): Creating level 1 of 2 levels
MG level 1 (GPU): 
Generate null vectors

And then the program halts.

**Comment by maddyscientist** [comment]
Hmm, can you try again disabling `CUDA_ENABLE_GDR`?

**Comment by cpviolator** [comment]
So add `CUDA_ENABLE_GDR=0` to my scripts and keeping `QUDA_ENABLE_GDR=1' ? Will do.

**Comment by maddyscientist** [comment]
Set `QUDA_ENABLE_GDR=0` or just comment out the setting entirely.

**Comment by cpviolator** [comment]
Same error. These envars shouldn't have any effect on compilation, should they?

**Comment by maddyscientist** [comment]
To confirm, it's now printing "Disabling GPU-Direct RDMA access".

**Comment by cpviolator** [comment]
OK, I set explicitly `QUDA_ENABLE_GDR=0` in the submission script and yes, RDMA is disables. The first null vector is calculated, then the solver diverges...

**Comment by maddyscientist** [comment]
Ok, I'll do some tests on Piz Daint myself then.  Thanks for reporting.

**Comment by cpviolator** [comment]
I'll try it it on Stampede too. If they don't have a GDR enabled MPI
implementation, I'll build openMPI and mvpich2 and try those.

**Comment by cpviolator** [comment]
Stampede's MVPICH2 is not cuda enabled, and either is Piz-Daint's. Looks
like a build from source is in order until sysadmin can string one
together. I'll submit tickets.

**Comment by maddyscientist** [comment]
Does it work fine on stampede with GDR disabled?

**Comment by cpviolator** [comment]
On Stampede with:

CUDA 7.5
QUDA_ENABLE_GDR=0
MVAPICH2/2.1
gcc/4.9.3

The first attempt with link recon 8 diverged, but with recon 12 the job
completes. Here's the command:

ibrun /work/03653/howarth/RDMA/build/tests/multigrid_invert_test
--mg-levels 2 --mg-block-size 0 2 2 2 4 --mg-nvec 0 24 --mg-nu-pre 4
--mg-nu-post 4 --mg-generate-nullspace true --mg-setup-inv 0 bicgstab
--dslash-type twisted-clover --solve-type direct --prec double
--prec-sloppy single --prec-precondition single --recon 12 --recon-sloppy
12 --xdim 8 --ydim 8 --zdim 4 --tdim 8 --Lsdim 1 --xgridsize 1 --ygridsize
1 --zgridsize 2 --tgridsize 2 --tolhq 0.2 --tol 1e-9 --niter 10000

I also got QUDA to compile against MVAPICH2/2.1-GDR with CUDA-7.0. The
MVAPICH2/2.2-GDR with CUDA-8.0 failed. With settings:

CUDA 7.0
QUDA_ENABLE_GDR=1 (and all the other envars)
MVAPICH2/2.1-GDR
gcc/4.9.3

and run the same command, but `ibrun` didn't play ball:
TACC: Starting up job 8498408
TACC: Could not determine MPI stack. Exiting!

probably because I'm using a custom MPI implementation.

Looks like these supercomputer admins need to step up their game and
install some GCR enabled MPI modules. I'm already writing tickets with
justifications.

**Comment by maddyscientist** [comment]
Ah, `--recon 8` diverging is a feature 😄 It's because if you don't load a lattice, then a free field is used, but this has a singularity for a free field theory owing to how it's parametrized.  So things looks fine on Stampede.....

Does `--recon 12` also diverge on Piz Daint?  Just wondering if this is just a machine issue for GDR and this recon 8 issue otherwise.

**Comment by cpviolator** [comment]
Just did the following on Piz-Daint, all worked out OK.

`Run command is:
srun -n 4 --ntasks-per-node=1 -c 12 multigrid_invert_test --dslash-type twisted-clover --prec double --prec-sloppy single --prec-precondition single --recon 12 --recon-sloppy 12 --recon-prec\
ondition 12 --xdim 16 --ydim 16 --zdim 8 --tdim 16 --xgridsize 1 --ygridsize 1 --zgridsize 2 --tgridsize 2 --mu 0.0009 --mg-levels 3 --mg-block-size 0 2 2 2 4 --mg-block-size 0 2 2 2 2 --mg-\
nu-pre 2 --mg-nu-post 2 --mg-setup-tol 5e-7 --mg-setup-inv 0 bicgstab --mg-setup-inv 1 bicgstab --mg-mu-factor 0 1.0 --mg-mu-factor 0 4.0`
`Sun May 21 02:15:11 CEST 2017`
`Disabling GPU-Direct RDMA access`

**Comment by maddyscientist** [comment]
@cpviolator, can you report the issue with respect to Piz Daint automatically disabling RDMA.  This is a clearly a system issue and will cause segmentation faults as well as worse performance.  I guess they must have upgraded their system as this wasn't a problem circa a month ago.

Thanks for confirming that Piz Daint is fine otherwise.

**Comment by cpviolator** [comment]
I requested that they either point me to a GDR enabled build of MPICH (because I can't find one), build a new module, or advise on how to use an MPICH build from my home directory.

I scoured their MPICH build and the passed the flag `--enable-cuda-weak` during compilation. Not sure what the difference is between `--enable-cuda-weak` and `--enable-cuda`.

**Comment by maddyscientist** [comment]
@cpviolator Fixed one issue related to your observations above: using CG as a smoother was broken, but is now fixed.

**Comment by cpviolator** [comment]
Awesome!

Comparing Piz-Daint and Stampede (p100 Vs K40) indicates that there's some
issue with Piz-Daint's setup, it's consistently slower.

I'll create some verbose output to see where the issue is and harass
Piz-Daint admin.

**Comment by cpviolator** [comment]
Oddly, after some scheduled maintenance on Piz-Daint,
`multigrid_invert_test` is now performing quickly again. Not tested the
full RDMA though. We have minor production jobs to perform so I'll keep
this thread updated as we go.

**Comment by mathiaswagner** [comment]
I am afraid that this is another way too big pull request to do a code review.
Unless anyone objects we might just have to merge that and live with it.

**Pull request merged**
