### PR TITLE
Codefest/milc base

### PR DESCRIPTION
**Pull request by mfrasca60**
I am trying to build an executable from MILC code but what I get in the end for the linker is

g++ -o su3_hmc  \
control.o setup.o gauge_info.o check_unitarity.o d_plaq4.o field_utilities.o io_detect.o io_helpers.o io_lat4.o io_lat_utils.o make_lattice.o nersc_cksum.o ploop2.o remap_stdio_from_args.o reunitarize2.o ranstuff.o  layout_hyper_prime.o  io_ansi.o  com_vanilla.o    update.o  update_u.o update_h.o ranmom.o d_action.o ../libraries/su3.1.a ../libraries/complex.1.a           -Wl,-rpath /home/mf/working/quda/lib -L/home/mf/working/quda/lib -lquda -L/usr/local/cuda/lib64 -L/lib64 -L/lib -lcudart -lcuda -lcublas -lcufft -ldl      -lm
/usr/bin/ld: make_lattice.o: in function `make_lattice':
make_lattice.c:(.text+0x23): undefined reference to `initialize_quda'
collect2: error: ld returned 1 exit status
make[1]: *** [Make_template:184: localmake] Errore 1
make[1]: uscita dalla directory «/home/mf/working/milc_qcd/pure_gauge»
make: *** [Make_template:143: su3_hmc] Errore 2

that seems rather odd as all the paths seem right. Could you help me please?

### CODE REVIEW

**Comment by mathiaswagner** [comment]
Jenkins: Can one of the admins verify this patch?

**Comment by mathiaswagner** [comment]
Jenkins: Can one of the admins verify this patch?

**Comment by maddyscientist** [comment]
Hi @mfrasca60,

The `initialize_quda` function is part of MILC and not part of QUDA.  It is defined in `generic/milc_to_quda_utilities.c`, are you including its object file when you link here?

Aside: I imagine this should be an issue and not a pull request.

**Comment by mfrasca60** [comment]
Hi @maddyscientist,

Thanks a lot. You are right: It is an issue. Sorry for the wrong choice but I am starting now with MILC and QUDA. Your suggestion worked like a charm.

**Comment by maddyscientist** [comment]
Great, glad this worked out.  Closing.

**Pull request closed without merging**
