### PR TITLE
improve rpath handling

### LINKED ISSUE #1274: installed executables have RUNPATH pointing to nonexistent directories
With `QUDA_DOWNLOAD_USQCD`, `make install` installs things under `usqcd` by default, and we have `usqcd/bin`, `usqcd/lib`, and `usqcd/include`.  However, the `RUNPATH` of installed binaries, eg. from `readelf -d usqcd/bin/blas_test`, points to `usqcd/lib64`, which does not exist.  As a result, directly running `tests/blas_test` after build works fine, but `make install` creates executables that have the wrong RPATH and cannot run without changing the environment or its RPATH.

### PR DESCRIPTION
**Pull request by mathiaswagner**
Set default RPATH variables early so QUDA targets and USQCD dependencies pick them up.
Should resolve #1274 #1275 

For reference: https://gitlab.kitware.com/cmake/community/-/wikis/doc/cmake/RPATH-handling

### CODE REVIEW

**Comment by mathiaswagner** [comment]
@jxy could you please give that a try and see whether this fixes your RUNPATH issues?

**Comment by mathiaswagner** [comment]
@bjoo thoughts on this? QUDA sets all the CMAKE RPATH variables early so the USQCD dependencies pulled in through CPM can pick them up.

**Comment by bjoo** [comment]
Sounds like a good idea. Rpath issues have always plagued me...

--
Balint Joo,  Oak Ridge Leadership Computing Facility,
Oak Ridge National Laboratory
P.O. Box 2008, 1 Bethel Valley Road, Oak Ridge, TN 37831, USA
email: joob AT ornl.gov.  Tel: +1-757-912-0566 (cell, remote)

From: Mathias Wagner ***@***.***>
Reply-To: lattice/quda ***@***.***>
Date: Tuesday, May 10, 2022 at 4:07 PM
To: lattice/quda ***@***.***>
Cc: Balint Joo ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [lattice/quda] improve rpath handling (PR #1276)
Resent-From: ***@***.***>
Resent-Date: Tuesday, May 10, 2022 at 4:06 PM


@bjoo<hxxps://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_bjoo&d=DwMCaQ&c=CJqEzB1piLOyyvZjb8YUQw&r=WG01dcOd8ZFLFFNkrpbj6A&m=BiDRQGJth3GHstpqSBw7GASVqI_Wdd2UjOFV6KDE4wxZqhaAo7bJgH7yWMEI6STn&s=OXagx4wn_phPz90rR4znRD0RVNnSeCvdeNg0rOkuy3o&e=> thoughts on this? QUDA sets all the CMAKE RPATH variables early so the USQCD dependencies pulled in through CPM can pick them up.

**Comment by mathiaswagner** [comment]
@jxy could you please have look at this?

**Comment by jxy** [comment]
Now the rpath points to `/usr/local/lib` even though `make install` installs the binaries under the local `usqcd` directory by default.

**Comment by mathiaswagner** [comment]
I cannot reproduce this. I did a fresh build with DOWNLOAD_USQCD enabled and installed everything to `usqcd`.
Checking the binaries in `usqcd/bin` with `objdump -x` I get

```
  RUNPATH              /home/mathiasw/qudabuildfast/hotfix/rpath/usqcd/lib
  RUNPATH              /usr/local/openmpi/lib:/home/mathiasw/qudabuildfast/hotfix/rpath/usqcd/lib:/usr/local/cuda/lib64:/usr/local/openmpi/lib
  RUNPATH              /usr/local/openmpi/lib:/home/mathiasw/qudabuildfast/hotfix/rpath/usqcd/lib:/usr/local/cuda/lib64:/usr/local/openmpi/lib
  RUNPATH              /usr/local/openmpi/lib:/home/mathiasw/qudabuildfast/hotfix/rpath/usqcd/lib:/usr/local/cuda/lib64:/usr/local/openmpi/lib
  RUNPATH              /home/mathiasw/qudabuildfast/hotfix/rpath/usqcd/lib
  RUNPATH              /usr/local/openmpi/lib:/home/mathiasw/qudabuildfast/hotfix/rpath/usqcd/lib:/usr/local/cuda/lib64:/usr/local/openmpi/lib
  RUNPATH              /home/mathiasw/qudabuildfast/hotfix/rpath/usqcd/lib
  RUNPATH              /usr/local/openmpi/lib:/home/mathiasw/qudabuildfast/hotfix/rpath/usqcd/lib:/usr/local/cuda/lib64:/usr/local/openmpi/lib
  RUNPATH              /usr/local/openmpi/lib:/home/mathiasw/qudabuildfast/hotfix/rpath/usqcd/lib:/usr/local/cuda/lib64:/usr/local/openmpi/lib
  RUNPATH              /usr/local/openmpi/lib:/home/mathiasw/qudabuildfast/hotfix/rpath/usqcd/lib:/usr/local/cuda/lib64:/usr/local/openmpi/lib
  RUNPATH              /usr/local/openmpi/lib:/home/mathiasw/qudabuildfast/hotfix/rpath/usqcd/lib:/usr/local/cuda/lib64:/usr/local/openmpi/lib
  RUNPATH              /home/mathiasw/qudabuildfast/hotfix/rpath/usqcd/lib
  RUNPATH              /home/mathiasw/qudabuildfast/hotfix/rpath/usqcd/lib
  RUNPATH              /usr/local/openmpi/lib:/home/mathiasw/qudabuildfast/hotfix/rpath/usqcd/lib:/usr/local/cuda/lib64:/usr/local/openmpi/lib
  RUNPATH              /usr/local/openmpi/lib:/home/mathiasw/qudabuildfast/hotfix/rpath/usqcd/lib:/usr/local/cuda/lib64:/usr/local/openmpi/lib
  RUNPATH              /home/mathiasw/qudabuildfast/hotfix/rpath/usqcd/lib
  RUNPATH              /usr/local/openmpi/lib:/home/mathiasw/qudabuildfast/hotfix/rpath/usqcd/lib:/usr/local/cuda/lib64:/usr/local/openmpi/lib
  RUNPATH              /usr/local/openmpi/lib:/home/mathiasw/qudabuildfast/hotfix/rpath/usqcd/lib:/usr/local/cuda/lib64:/usr/local/openmpi/lib
  RUNPATH              /usr/local/openmpi/lib:/home/mathiasw/qudabuildfast/hotfix/rpath/usqcd/lib:/usr/local/cuda/lib64:/usr/local/openmpi/lib
```

Similar for the examples.

Can you please provide a description of what exactly you did and which rpath is not ok?

**Comment by jxy** [comment]
code:

```
$ git status
On branch hotfix/rpath
Your branch is up to date with 'origin/hotfix/rpath'.

nothing to commit, working tree clean
$ git show
commit 0535e5c40d90cdaa6602cab684d1fac63780de3f (HEAD -> hotfix/rpath, origin/hotfix/rpath)
Merge: 2721c7110 aa9d9c03f
Author: Mahias Wagner <mathiasw@nvidia.com>
Date:   Mon May 23 16:00:02 2022 +0200

    Merge branch 'develop' into hotfix/rpath

```

cmake
```
cmake\
        -DCMAKE_BUILD_TYPE=RELEASE\
        -DQUDA_GPU_ARCH=sm_80\
        -DQUDA_DOWNLOAD_USQCD=on\
        -DQUDA_QMP=on\
        -DQUDA_QIO=on\
        -DQUDA_MULTIGRID=on\
        -DCMAKE_CXX_COMPILER=mpic++\
        -DCMAKE_C_COMPILER=mpicc\
        ../quda
```
build
```
make -j256 install
```
rpath
```
$ readelf -d usqcd/bin/blas_test|grep RUNPATH
 0x000000000000001d (RUNPATH)            Library runpath: [/usr/local/lib:/soft/libraries/mpi/openmpi/4.1.1/lib]
$ readelf -d usqcd/bin/lime_contents|grep RUNPATH
 0x000000000000001d (RUNPATH)            Library runpath: [/usr/local/lib:/soft/libraries/mpi/openmpi/4.1.1/lib]
```
What did I miss?

**Comment by mathiaswagner** [comment]
~Ok, there seems to be some difference when using `make` vs `ninja` here.
I usually build with ninja but think I can reproduce with `make`.~
This was just initial run as I did things in the wrong order.

**Comment by mathiaswagner** [comment]
Fix pushed. Hope this works now.

**Comment by jxy** [comment]
It looks good to me now.

**Comment by mathiaswagner** [comment]
Thanks for checking.

**Review by maddyscientist — APPROVED** [review]
This looks good

**Pull request merged**
