### PR TITLE
Added stout smearing routines. This includes a new function in quda_m…

### PR DESCRIPTION
**Pull request by cpviolator**
…atrix.h that performs the exponentiation of SU(3) matrix using Caley-Hamilton.

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/lattice/quda/pull/416" target="_blank">ReviewNinja

**Comment by mathiaswagner** [comment]
Jenkins: Can one of the admins verify this patch?

**Comment by maddyscientist** [comment]
Something looks wrong here.  This change deletes a bunch of recent changes notably in the interface.

@cpviolator what branch did you base your pull request on?

**Comment by cpviolator** [comment]
Ahh, I branched from develop, but I think I've copied a file from an old
version of QUDA. Let me clean it up and make a new pull request.

**Comment by mathiaswagner** [comment]
@cpviolator With #418 I guess this can be closed without merging?

**Pull request closed without merging**
