### PR TITLE
Trigger reliable updates only from shift 0 in multi shift cg

### PR DESCRIPTION
**Pull request by mathiaswagner**
This is sufficient with the current implementation. Still keep the loop and arrays to be able to trigger on higher shifts again in the future without having to add back in that code.

The multi shift solve needs less reliable updates and is slightly faster (time including the refinement phase)

### CODE REVIEW

**Comment by mikeaclark** [comment]
Any thoughts on how we can make the refinement do double-half, but double-single in the solve?  Is this an easy patch?

**Comment by mikeaclark** [comment]
Style comment: you've used 6 space indent here not the usual 2 space indents as is generally used (and advocated).

**Comment by mathiaswagner** [comment]
sorry, that is messed up because the files is partially indented using tabs and I have set my tab width to two ....
I'll remove the tabs.

**Comment by mathiaswagner** [comment]
No idea yet what is the easiest way to use a different sloppy precision ...

**Comment by mikeaclark** [comment]
I guess we can either:
* use the cuda_prec_precondition precision for the refinement 
* make a new parameter in `QudaInvertParam`

I realize I should introduce this discussion elsewhere.  :)

**Pull request merged**
