### PR TITLE
Hotfix/misc 1.1

### PR DESCRIPTION
**Pull request by maddyscientist**
Some fixes for the 1.1 release
* Remove `GPU_MULTIGRID_DOUBLE` definition when `HOST_DEBUG` is enabled.  We will enable proper double precision MG capability in 2.0
* Backport tuning fixes from generic kernels branch to avoid some `TuneParam` aliasing when doing nested tunings.
* Backport shmem_helper.cuh fix from generic kernels to avoid any potential header conflict between `cuda/atomic` and host std headers (only include `cuda/atomic` when using a CUDA-aware compiler).

### CODE REVIEW

**Review by cpviolator — APPROVED** [review]
All pretty uncontroversial.

**Comment by weinbe2** [comment]
@maddyscientist this still needs the warning about (harmless) incorrect coarse gauge norms when doing MMA-accelerated MG builds --- otherwise looks good after a cursory review! I'll do a more thorough review tomorrow.

**Review by mathiaswagner — CHANGES_REQUESTED** [review]
all good but setting to 'request changes' so we don't miss the changes @weinbe2 already requested

**Comment by mathiaswagner** [comment]
@maddyscientist any updates here?

**Comment by weinbe2** [comment]
@mathiaswagner to some degree this is on me, I can finally get to my review today

**Review by weinbe2 — APPROVED** [review]
Looks good. Thanks for all these fixes @maddyscientist

**Pull request merged**
