### PR TITLE
avoid QMP/QIO configure in every make invocation

### PR DESCRIPTION
**Pull request by mathiaswagner**
When QUDA_DOWNLOAD_USQCD is enabled avoid running configure multiple times by pointing QUDA_QMPHOME / QUDA_QIOHOME / QUDA_LIMEHOME to the result of the previous build and remove the target dependency on QMP/QIO from QUDA

### CODE REVIEW

**Comment by mathiaswagner** [comment]
About to board my plane. Quick check looked ok but it might need more in the wild testing. Hence only a draft for now.

**Comment by maddyscientist** [comment]
Excellent addition 😄

**Comment by mathiaswagner** [comment]
Was to quick yesterday. A bit more testing revealed that it did not work reliably. It does work now but requires to manually `cmake .` once QIO/QMP have been build (unless anything else triggers a rerun of cmake already).

**Comment by mathiaswagner** [comment]
This should now work as intended.

**Comment by weinbe2** [comment]
Noticed this was still pending, so adding a quick ping to @maddyscientist and @cpviolator . `QUDA_DOWNLOAD_USQCD` has some quirks on my end that I think are just related to my machine setup as opposed to something fundamental, but it does block me from giving this an approval myself.

**Comment by cpviolator** [comment]
Works perfectly for me using `ccmake` on NVSOCAL2.

**Comment by cpviolator** [comment]
@maddyscientist Happy with this?

**Pull request merged**
