### PR TITLE
improve linking against cufft and curand

### PR DESCRIPTION
**Pull request by mathiaswagner**
This should fix having to run cmake twice for cufft and curand.

@kostrzewa do you mind giving it a try?

### CODE REVIEW

**Comment by kostrzewa** [comment]
will do

**Comment by weinbe2** [comment]
@mathiaswagner I believe we should be linking `curand` no matter what because it gets used for generating random spinor fields. I can get to this a little later if you don't have the cycles to quickly pop it in now.

**Review by kostrzewa — APPROVED** [review]
works for me on PizDaint

**Comment by mathiaswagner** [comment]
Looking at the code more I think we don't even need to link against curand at all. We only use the device interface.

 @maddyscientist @weinbe2 Do you agree? If yes I'd just remove that dependency. I have test a build locally and it seems fine.

**Comment by weinbe2** [comment]
@mathiaswagner if it's building and running fine, sounds good, I don't know if @maddyscientist has other plans in mind.

**Comment by maddyscientist** [comment]
I hadn’t realized this, but I think this is correct that we only use the device interface.  I think this is something that @nmrcardoso probably added and we percolated without thinking too hard.

**Review by maddyscientist — APPROVED** [review]

**Pull request merged**
