### PR TITLE
Move über kernel into a separate kernel instantiation

### PR DESCRIPTION
**Pull request by mathiaswagner**
This allows to completely remove the exterior path from the  non-uber interior kernels by creating two different template instances for uber and non-user kernels.

WIP as I still need to check perf before this is ready.

### CODE REVIEW

**Comment by hummingtree** [comment]
I will do a multi-GPU run comparison between `this` with nvshmem, and `release11x` with no nvshmem, for DWF.

**Comment by hummingtree** [comment]
`--gridsize 1 1 1 1 --Lsdim 12` 
| Precon        | Precision           | L^4  | shmem-reg-GFLOPS | release11x-no-nvshmem-GFLOPS | speed up |
| :-: |:-:| :-:| :-: |:-:| :-:|
| 4D | double | 16 | 1279.8 | 1276.2 | 1.00 |
| 4D | double | 24 | 1169.6 | 1127.6 | 1.04 |
| 4D | double | 32 | 1190.3 | 1116.2 | 1.07 |
| 4D | single | 16 | 2872.7 | 2902.1 | 0.99 |
| 4D | single | 24 | 2609.2 | 2575.2 | 1.01 |
| 4D | single | 32 | 2676.3 | 2642.4 | 1.01 |
| 4D |   half | 16 | 3899.8 | 3871.8 | 1.01 |
| 4D |   half | 24 | 4096.5 | 4088.8 | 1.00 |
| 4D |   half | 32 | 4096.5 | 4015.2 | 1.02 |
| 5D | double | 16 | 1208.4 | 1131.1 | 1.07 |
| 5D | double | 24 | 1159.5 | 1072.4 | 1.08 |
| 5D | double | 32 | 1190.4 | 1077.0 | 1.11 |
| 5D | single | 16 | 2843.5 | 2827.2 | 1.01 |
| 5D | single | 24 | 2603.5 | 2581.8 | 1.01 |
| 5D | single | 32 | 2703.3 | 2712.1 | 1.00 |
| 5D |   half | 16 | 3767.9 | 3799.7 | 0.99 |
| 5D |   half | 24 | 3745.2 | 3721.4 | 1.01 |
| 5D |   half | 32 | 3871.3 | 3819.7 | 1.01 |

**Comment by hummingtree** [comment]
`--gridsize 1 2 2 2 --Lsdim 12` 
| Precon        | Precision           | L^4  | shmem-reg-GFLOPS | release11x-no-nvshmem-GFLOPS | speed up |
| :-: |:-:| :-:| :-: |:-:| :-:|
| 4D | double | 16 |  971.9 |  908.4 | 1.07 |
| 4D | double | 24 |  971.0 |  929.2 | 1.05 |
| 4D | double | 32 | 1053.4 |  993.1 | 1.06 |
| 4D | single | 16 | 2073.6 | 1786.5 | 1.16 |
| 4D | single | 24 | 2116.3 | 2036.4 | 1.04 |
| 4D | single | 32 | 2287.7 | 2244.5 | 1.02 |
| 4D |   half | 16 | 2988.2 | 2461.8 | 1.21 |
| 4D |   half | 24 | 3283.7 | 3246.0 | 1.01 |
| 4D |   half | 32 | 3601.5 | 3455.0 | 1.04 |
| 5D | double | 16 |  948.2 |  850.7 | 1.11 |
| 5D | double | 24 |  974.4 |  909.0 | 1.07 |
| 5D | double | 32 | 1044.7 |  966.0 | 1.08 |
| 5D | single | 16 | 2066.2 | 1817.1 | 1.14 |
| 5D | single | 24 | 2121.4 | 2051.1 | 1.03 |
| 5D | single | 32 | 2318.7 | 2314.9 | 1.00 |
| 5D |   half | 16 | 2898.1 | 2520.1 | 1.15 |
| 5D |   half | 24 | 3153.8 | 3044.4 | 1.04 |
| 5D |   half | 32 | 3401.2 | 3342.5 | 1.02 |

**Review by hummingtree — APPROVED** [review]
All looks good to me.

**Review by maddyscientist — APPROVED** [review]

**Pull request merged**
