### PR TITLE
Hotfix/real valued block blas

### PR DESCRIPTION
**Pull request by alexstrel**
This pull request fixes real valued  block dot product. It also introduces a real-valued axpy block-blas routine.

### CODE REVIEW

**Comment by maddyscientist** [comment]
Nice addition @alexstrel 😄

Can you add unit tests for these in `blas_test`?

Thx

**Comment by maddyscientist** [comment]
@cpviolator When this is merged, you should update the Lanczos solver to use these where appropriate.

**Comment by maddyscientist** [comment]
@alexstrel any update on getting the additions for blas_test?  

FYI: I have a branch that I have been working on that will completely and utterly conflict with this pull 😜: adding support for much large multi-blas-n sizes (> 128) and some general cleanup.

**Comment by alexstrel** [comment]
@maddyscientist made changes for test routines

**Pull request merged**
