### PR TITLE
removing hipMemset2D - appears to be unnecessary

### PR DESCRIPTION
**Pull request by CRobeck**
Performance improvements shown for small dimensions (e.g 16). Less significant for large dimensions.

### CODE REVIEW

**Comment by mathiaswagner** [comment]
Jenkins: Can one of the admins verify this patch?

**Comment by mathiaswagner** [comment]
Not running Jenkins on that as it is HIP specific.

**Comment by mathiaswagner** [comment]
@CRobeck @bjoo just wondering if this is integrated into #1092 and we can close this PR.

**Comment by bjoo** [comment]
At this point in time, it appears that hips `hipMemset2D` works so I will not merge this, and close this PR

**Pull request closed without merging**
