### PR TITLE
New Over-Improved-Symanzik stout smearing

### PR DESCRIPTION
**Pull request by cpviolator**
This routine implements the Over-Improved stout smearing outlined in https://arxiv.org/pdf/0801.1165.pdf. Topological charge calculations have been added after each link smearing routine in `su3_test` for quick comparisons.

### CODE REVIEW

**Comment by cpviolator** [comment]
Not sure why that build failed, all is good my end...

**Comment by maddyscientist** [comment]
@mathiaswagner This looks like a Jenkins / cmake issue.  Can you see what went wrong with these build tests?

@cpviolator The code itself looks good.  Will just wait until the build test issue is cleared up before we get this merged.  I presume performance is good with this?

**Comment by cpviolator** [comment]
Performance is as expected. 3D stout has 2x4 = 8 SU(3) multiplications per
link, but over improved 4D has 2x6 + 3x4x6 = 84. It is about 8 times slower
per step, so a touch faster than the expected 10.5 due to recycling links
once communicated.

**Comment by mathiaswagner** [comment]
@maddyscientist Looks like I screwed up the Jenkins configuration. CUDA was not found. Hope to have that fixed now.

**Pull request merged**
