### PR TITLE
Feature/cov dev ops rerwite

### PR DESCRIPTION
**Pull request by cpviolator**
Updates the covariant derivative and laplace dslash operators to the new C++ accessor framework.

For an efficient implementation of the covariant derivatives, this pull request adds support for non-spin projected halo exchange with overlapping comms and compute.  A further optimization would be to restrict communication to one direction only, and not just one dimension.  This is left as further work.

### CODE REVIEW

**Comment by cpviolator** [comment]
Just pinging Tean QUDA @mathiaswagner @maddyscientist @weinbe2 before this gets forgotten.

**Comment by weinbe2** [comment]
Thanks for the reminder @cpviolator . I can take a look at this next week after #794 gets merged in.

**Comment by cpviolator** [comment]
@mattias, Just noticed a block of commented out code in `laplace.cu` 149-243. I'll delete and push the change.

**Comment by maddyscientist** [comment]
Great work @cpviolator 😄

**Pull request merged**
