### PR TITLE
Feature/cmake

### PR DESCRIPTION
**Pull request by mathiaswagner**
I believe the cmake build is no ready for broader testing. 
There are still some open issues in #323 but most things should work by now.

It does not interfere with the current build system if using with out of source builds, e.g. like

```
mkdir <build-dir>; cd <build-dir>
cmake <quda-src>
```

Further options can be edited using e.g. `ccmake`, a graphical cmake version or editing `CMakeCache.txt`.

### CODE REVIEW

**Comment by mikeaclark** [comment]
Ok, I've started some testing.  Some comments:
* I guess the ordering of the CMakeCache.txt file is alphabetical.  This means that the the interface options are not contiguous, and neither are the Dirac operator options.  This makes setting options a bit of a pain.  Can this ordering be made custom?
* When editing the `CMAKE_BUILD_TYPE` there is a typo 
"CMAKE_BUILD_TYPE: Choose the type of build, options are: Devel **Relaese** Debug Release HostDebug DeviceDebug"

**Comment by mikeaclark** [comment]
A more serious issue: the plaquette seems to fail to build using cmake, but compiles fine with make.  The error it gives complains about the amount of shared memory use by the kernel:
```c++
ptxas error   : Entry function '_ZN4quda11computePlaqILi960EfNS_11FloatNOrderIfLi18ELi4ELi8EEEEEvNS_12GaugePlaqArgIT1_EE' uses too much shared data (0xc320 bytes, 0xc000 max)
`
It's only complaining about the kernels with 960, 992 and 1024 threads per block.

**Comment by mathiaswagner** [comment]
* The ordering in the CMakeCache.txt unfortunately is a pain. The only option are better names for the options (i.e. prefix everything with QUDA). The GUI (I guess that will not really be used) has an option to generate at least one level of folding (using '_' as separator). See screenshot.
screen shot 2015-09-16 at 19 52 20

* I should fix that.

* CMake supports a boolean type (the on / off), strings, paths but unfortunately (I have been looking for that) no dropdown lists. We can however add a check within in cmake whether it is a valid build type.

**Comment by mikeaclark** [comment]
So it sounds like to group together the build options we need to rename them.  E.g., to get the Dirac operators together we should use `BUILD_STAGGERED_DIRAC` -> `BUILD_DIRAC_STAGGERED`.

**Comment by mathiaswagner** [comment]
We should probably rename all options for QUDA to be prefixed with QUDA.
Not sure whether we should rely on the grouping even more and use also QUDABUILD (which will show up as another group (cf screenshot above)).

**Comment by mathiaswagner** [comment]
I have added a check for a vlid build type.

**Comment by mikeaclark** [comment]
It's question time!
* Am correct in thinking that the build option names using cmake are completely independent of the names using configure/make?  So there's nothing to stop us from renaming these for cmake without touching the configure/make build system is there?
* What's the process of adding subdirectories using cmake?  Just thinking about source code clean up and moving to a more hierarchical structure.
* With cmake can we still build in the source quda directory if we want to (we just can't do this while also expecting to be able to use confugure/make.  Is that correct?

**Comment by mathiaswagner** [comment]
Answer time:
* Yes. They are mostly the same now for historical reasons. As long as they trigger the correct defines. 
* We can do in-source builds. I currently have an option to forbid that as this would overwrite the current Makefiles.

**Comment by mathiaswagner** [comment]
Subdirectories for sources should be easy. We could just specify the sources in the lib/CMakeLists.txt with path or we can use glob (I'd rather not).

**Comment by mathiaswagner** [comment]
Oh and for headers we just have to tell cmake where to look. All dependencies should come for free.

**Comment by mathiaswagner** [comment]
@mikeaclark I just managed to trigger the error for gaugeplag. I started with a fresh build directory and ran cmake. The NVCC_FLAGS were missing.
The problem could be fixed by running 'cmake .' again in the build directory. I need to figure out what is going on here.

**Comment by bjoo** [comment]
HI Mathias, Kate,
 I have been trying to play with CMake, and wanted to try better integration with QMP. 
 I saw how Mathias did this in the CMakeLists file. I went for another approach, which 
is that I added a QMPConfig.cmake file to qmp (look in feature/cmake-config branch 
at github.com:usqcd-software/qmp.git )

This sets a bunch of CMake variables:

QMP_C_COMPILER   — the C compiler used to compile QMP
QMP_C_COMPILE_FLAGS — the compiler flags used to compile QMP       (turned into a list for ease of appending)
QMP_C_LINK_FLAGS         — linker flags used to link QMP test programs  (turned into a list for ease of appending)
QMP_C_LIBRARIES            — the various -l options to link wiht QMP          ( turned into a list for ease of appending)
QMP_C_INCLUDE_PATH    — the location of the include/ directory   
QMP_C_FOUND

In my test setup I used this the following way:

i) when I invoke cmake, I need to specify:   

> -DQMP_DIR="/home/bjoo/package-8-7-15/avx/install/qmp”


 to tell automake where to look, tho this can also be done by cc-make or the GUI or by appending to the CMAKE_PREFIX_PATH directly
  
ii) In my CMakeLists.txt I explicitly add QMP_DIR onto the prefix path if the user has defined QMP_DIR

>    if( QMP_DIR )
>      set( CMAKE_PREFIX_PATH "${CMAKE_PREFIX_PATH}" "${QMP_DIR}")
>    endif( QMP_DIR )
> 

iii) I can then do regular CMake 'find_package(QMP)’ and take regular configuration actions.


> # Find package QMP
> find_package( QMP REQUIRED )
> 
> # Check for QMP
> if ( ${QMP_C_FOUND} )
>   include_directories(${QMP_C_INCLUDE_PATH})
>   LIST(APPEND EXT_LIBS ${QMP_C_LINK_FLAGS} )
>   LIST(APPEND EXT_LIBS ${QMP_C_LIBRARIES} )
> endif( ${QMP_C_FOUND} )

So in the above case I add the include path to the global include_directories
and append the link options to a variable called EXT_LIBS

iv) when I then need to link an application I can do e.g. for some gtest program:

> add_executable(foo_test foo_test.cpp
> "${CMAKE_SOURCE_DIR}/external/gtest/gtest-all.cc")
> )
> add_compile_options(${EXT_CXXFLAGS})
> target_link_libraries(foo_test ${EXT_LIBS})

NB: Here I hava also an ${EXT_CXXFLAGS} which I didn’t set in step iii) but I may have it modified
by other find-packages (e.g. find_package ( Threads ) )

In any case I don’t know if this simpler than what is being done currently, but I am thinking it is heading more
towards the ‘CMake’ way (ie that packages like QMP should at least describe themselves etc). 

If you like this and it works for you, I’ll send a pull request to merge the addition of this QMPConfig.cmake file
into the master branch of QMP. 

Best, 
 B

> On Sep 18, 2015, at 12:43 AM, Mathias Wagner <notifications@github.com> wrote:
> 
> @mikeaclark I just managed to trigger the error for gaugeplag. I started with a fresh build directory and ran cmake. The NVCC_FLAGS were missing.
> The problem could be fixed by running 'cmake .' again in the build directory. I need to figure out what is going on here.
> 
> —
> Reply to this email directly or view it on GitHub.
> 

--------------------------------------------------------------------------------------
Dr Balint Joo              High Performance Computational Scientist
Jefferson Lab
12000 Jefferson Ave, Suite 3, MS 12B2, Room F217,
Newport News, VA 23606, USA
Tel: +1-757-269-5339,      Fax: +1-757-269-5427
email: bjoo@jlab.org       
-------------------------------------------------------------------------------------

**Comment by mathiaswagner** [comment]
I only had a quick look but if we can get QMP to provide the necessary configuration I always prefer that. 
Only issue is then we have to force people to use a recent enough QMP. 

I'm busy with some other thing this week but appreciate any feedback on cmake. 

Thanks, Balint!

**Comment by mathiaswagner** [comment]
I know the cmake still has some rough edges that need polishing but for the automated builds it might be useful to get the cmake support into develop and keep the cmake branch alive for further improvements.
As I will need to setup different builds anyway this will also test the different builds using cmake so the automated builds first (pre-release ;-) ) milestone will be to test all the cmake options.

Does that sound useful?

**Comment by mikeaclark** [comment]
As per @mathiaswagner's suggestion, merging this now, despite it not yet being perfect.  The present build system will continue to work while we migrate.

**Comment by mathiaswagner** [comment]
So, this adds a small additional duty to reviewers and developers: If you modify the current build system please add these changes to the Cmake based build system or let me know so I can help with that.

For our current pull requests (from @alexstrel , @AlexVaq , @mikeaclark ) that are affected it might be the best idea to merge develop into the feature branch and then add the changes to the CMakeLists. Again, I am happy to help you out there.

**Comment by mikeaclark** [comment]
Sounds like a good idea @mathiaswagner.  I guess this is similar to having to maintain the Fortran interface as well as the C interface.

**Comment by mathiaswagner** [comment]
I keep working in the 'feature/cmake' branch. The issue with nvcc flags not being set correctly should now be fixed.

**Pull request merged**
