### PR TITLE
potential size reuction for libquda

### PR DESCRIPTION
**Pull request by mathiaswagner**
always enable binary compression for fatbin

### CODE REVIEW

**Comment by maddyscientist** [comment]
Do you have any before / after numbers to demonstrate the effect of this?

**Comment by mathiaswagner** [comment]
I saw 2.7G vs 2.6G, so nothing huge. It might however sometimes prevent us from tripping over library size issues. It is a bit tricky to get a feeling for that as you need to do builds with most things enabled in QUDA and compare with and without that. And it requires a full recompile ...

**Comment by maddyscientist** [comment]
Any feel if there's any impact on module load time?

**Comment by mathiaswagner** [comment]
No, not really.

**Review by maddyscientist — APPROVED** [review]

**Pull request merged**
