### PR TITLE
FIX: Adding allocation for evals in MG when deflation is preserved

### PR DESCRIPTION
**Pull request by pittlerf**
In the current develop version I obtained the following error when updating MG with `preserve_deflation`.
```
MG level 1 (GPU): ERROR: Requesting 256 eigenvalues with only storage allocated for 0 (rank 0, host nid007567, eigensolve_quda.cpp:582 in void quda::EigenSolver::computeEvals(std::vector<ColorSpinorField> &, std::vector<Complex> &, int)())
```
Here I provide a small fix. Thank you,

### CODE REVIEW

**Comment by mathiaswagner** [comment]
Jenkins: Can one of the admins verify this patch?

**Comment by mathiaswagner** [comment]
Jenkins: Can one of the admins verify this patch?

**Comment by maddyscientist** [comment]
@Jenkins ok to test

**Comment by maddyscientist** [comment]
@pittlerf thanks for the contribution.  Please feel free add your name to the contributor list on the README 😄

**Review by maddyscientist — APPROVED** [review]

**Comment by maddyscientist** [comment]
@Jenkins ok to test

**Comment by kostrzewa** [comment]
This does not seem to be enough to make it work for me. I need to additionally resize `evals` before or when `EigenSolver::computeEvals` is called.

**Comment by kostrzewa** [comment]
As a temporary workaround I do the following:

```
584   void EigenSolver::computeEvals(std::vector<ColorSpinorField> &evecs,
585                                  std::vector<Complex> &evals, int size)
586   {
587     if (size > (int)evecs.size())
588       errorQuda("Requesting %d eigenvectors with only storage allocated for %lu", size, evecs.size());
589     if (size > (int)evals.size())
590       evals.resize(size);                                                                                                              
591       //errorQuda("Requesting %d eigenvalues with only storage allocated for %lu", size, evals.size());
```

**Comment by weinbe2** [comment]
@kostrzewa @pittlerf trying to close the loop on this---I know the PR's been stagnant a bit, can one of you please merge in `develop` (which should "just work", it seems), add that change in `computeEvals`, and do a last test with your workflow (since I don't know what exactly it is)?

I can take care of cosmetic things like updating contributors + `clang-format` if that helps, I just can't confirm that the fixes here still work for you.

**Comment by kostrzewa** [comment]
@weinbe2 sorry, I completely lost sight of this for a number of reasons, have it on my TODO list now and will get back to you

**Comment by pittlerf** [comment]
> @kostrzewa @pittlerf trying to close the loop on this---I know the PR's been stagnant a bit, can one of you please merge in `develop` (which should "just work", it seems), add that change in `computeEvals`, and do a last test with your workflow (since I don't know what exactly it is)?
> 
> I can take care of cosmetic things like updating contributors + `clang-format` if that helps, I just can't confirm that the fixes here still work for you.

Hi, yes, sorry I also lost sight of this, however with @kostrzewa additions still works for our framework.

**Comment by kostrzewa** [comment]
@weinbe2 I can confirm that this still works correctly with tmLQCD after the merge with develop. I've removed the commented-out error message and added a comment to explain why the `evals.resize()` is necessary. Not sure if the latter is really helpful.

Should I squash these into a single commit and force-push?

**Comment by maddyscientist** [comment]
No need to force-push I think, we can I assume just do a "Squash and Merge"?

I've merged in latest develop, which should allow the CI matrix to complete.  Once that shows as green, we can just hit the button I think.

**Comment by maddyscientist** [comment]
@Jenkins test this please

**Review by maddyscientist — APPROVED** [review]

**Pull request merged**
