### PR TITLE
jitified and cleaned up the APE routine

### PR DESCRIPTION
**Pull request by cpviolator**
Jitify the APE routines.

### CODE REVIEW

**Comment by cpviolator** [comment]
@mathiaswagner That's right. The Stout code shifted the GPU kernel code from the `.cu` file to the `kernels` file. I just did the same.

Now that I've done this I'm seeing a lot of boiler plate code that can be shared among all the gauge algorithms. I'm working on porting a gauge fixing routine to the same style as the smearing routines, then we can think about a class that holds the boiler plate for all gauge algos.

I developed this on summit. Let me pull it to a machine with a `clang-format` executable.

**Comment by cpviolator** [comment]
Not having a good time with the class-format script:

```

**Comment by cpviolator** [comment]
@mathiaswagner Is this good to go? I want to update all the gauge field algorithms from this branch.

**Comment by weinbe2** [comment]
Due-diligence check, just because I've forgotten to do this in the past and it's come back to bite me: have you verified this works for both a single- and multi-GPU compile, jitify and non-jitify?

Also, it's not worth holding up this specific PR, but it'd be nice if there were CPU verify routines in the test files, at minimum for smearing and computing the topological charge, similar to the CPU dslash implementations. I know implementing CPU checks is a massive PITA (and they're slow, so I don't really see the need to implement a CPU gauge fix, for ex), but it'd be nice to have an independent confirmation on correctness.

**Comment by weinbe2** [comment]
@cpviolator, if you haven't already, can you do a quick check with a single GPU build? No need to roll back this merge, if there's an issue just do a quick hotfix branch and we'll get it plugged in quickly.

**Comment by cpviolator** [comment]
Turning on jitify breaks all the tests! (blas_test, gauge_alg_test, heatbath_test, pack_test, su3_test) Is this a known issue?

**Pull request merged**
