### PR TITLE
Feature/staggered eig test

### PR DESCRIPTION
**Pull request by cpviolator**
Unit test for staggered eigensolver. Some code duplication placed in utility file.

### CODE REVIEW

**Comment by maddyscientist** [comment]
Nice cleanup of the common staggered boilerplate.
* Why was a force push needed?
* I see clang-format needs to be applied yet.

**Comment by cpviolator** [comment]
Force push was just to change a typo in the commit message. Clang was pure negligence!

While we're here, I should try to clean up the dslash test too.

**Comment by cpviolator** [comment]
OK @maddyscientist @mathiaswagner @weinbe2 I think this is ready for review.

**Comment by maddyscientist** [comment]
Ok, I don't think this can be merged into the release/1.0.x branch.  @cpviolator it looks like this branch already contains recent work from the `develop` branch and is not simply the addition of the staggered eigensolver test.  Two options
* Strip out the develop branch additions, and make this branch just the addition of the eigensolver test
* Don't bother adding the staggered eigensolver test to the 1.0 release, just make it a post 1.0 thing.

Thoughts @cpviolator, @mathiaswagner, @weinbe2 ?

**Comment by weinbe2** [comment]
@maddyscientist agreed. I think it should be easy enough to just cherry-pick/copy+paste out the minimally required things (deflation test driver plus the consolidation of the HISQ construction routines).

**Comment by cpviolator** [comment]
Yeah, I wrote this off develop branch, then rebased to 1.0. I'll just start over.

**Comment by cpviolator** [comment]
Closing and referring to #864

**Pull request closed without merging**
