### PR TITLE
Feature/twisted-hasen

### PR DESCRIPTION
**Pull request by bjoo**
Continuation of pull #777 
I have merged twisted-hasen with the latest develop and pushed it as a feature branch 
into the quda repo. I couldn't alter #777 so I've closed it and am continuing it here.

### CODE REVIEW

**Comment by maddyscientist** [comment]
@bjoo I have merged in develop, and updated your new dslash kernels to use the simplified framework.  I've also fix some bugs and updated the ctest list to include asymmetric preconditioning testing.  Can you take a look, and confirm you are ok with this?

Also, one question: I see you've added a new instantiation to dslash_wilson_clover.cu, which include a twist term.  E.g., `WilsonCloverWithTwistApply`.  Isn't this identical to the already present dslash operator defined in dslash_twisted_clover.cu and so redundant?

Also, I propose that we only build these additional operators with either `QUDA_DIRAC_TWISTED_CLOVER` set or we introduce a new one for these one specifically, like `QUDA_DIRAC_CLOVER_TWISTED_HASENBUSCH` to control build time for folks who don't need these extra operators and just want to run straight clover.

**Comment by bjoo** [comment]
Excellent! Thanks very much @maddyscientist !


> On Sep 18, 2019, at 3:49 PM, maddyscientist <notifications@github.com> wrote:
> 
> @bjoo I have merged in develop, and updated your new dslash kernels to use the simplified framework. I've also fix some bugs and updated the ctest list to include asymmetric preconditioning testing. Can you take a look, and confirm you are ok with this?
> 
> Also, one question: I see you've added a new instantiation to dslash_wilson_clover.cu, which include a twist term. E.g., WilsonCloverWithTwistApply. Isn't this identical to the already present dslash operator defined in dslash_twisted_clover.cu and so redundant?
> 
> Also, I propose that we only build these additional operators with either QUDA_DIRAC_TWISTED_CLOVER set or we introduce a new one for these one specifically, like QUDA_DIRAC_CLOVER_TWISTED_HASENBUSCH to control build time for folks who don't need these extra operators and just want to run straight clover.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

-----------------------------------------------------------------------------
Dr Balint Joo   High Performance Computational Scientist
Jefferson Lab
12000 Jefferson Ave Suite 3, MS 12B2, Room F217
Newport News VA 23606, USA
Tel: +1-757-269-5339         email: bjoo AT jlab.org
-----------------------------------------------------------------------------

**Comment by bjoo** [comment]
The diffs looked good. I will see if I can pass my tests in the chroma twisted hasen branch...

**Comment by bjoo** [comment]
The chroma checks for this in `t_cmat_quda` and `t_multi_rhs` seem to pass so I will hit the big merge pull request button.

**Pull request merged**
