### PR TITLE
Hotfix/multigpu fix

### PR DESCRIPTION
**Pull request by maddyscientist**
This pull request closes issues #388 and #389.

### CODE REVIEW

**Comment by maddyscientist** [comment]
Assigning to @mathiaswagner

**Comment by mathiaswagner** [comment]
I compiled the code (to be fair using cmake) and get a lot of warnings. 

Some examples:
```
/home/mathias/quda/lib/gauge_fix_fft.cu:444:73: warning: format ‘%d’ expects argument of type ‘int’, but argument 4 has type ‘long unsigned int’ [-Wformat=]
       sprintf(aux_string,"threads=%d,prec=%d",arg.threads, sizeof(Float));

/home/mathias/quda/lib/gauge_fix_ovr_extra.h:7:28: warning: extra tokens at end of #include directive [enabled by default]
 #include <quda_internal.h> some conflicts with thrust library

/home/mathias/quda/lib/pgauge_heatbath.cu:416:10: warning: "/*" within comment [-Wcomment]

```

I know it it is annoying to fix that but getting rid of all these warnings is one of the mid-term goals we need to achieve to make the warnings actually useful again.

Please compile with all warnings enabled (CPU and GPU compilers) and try to reduce them.

**Comment by mathiaswagner** [comment]
One more maybe important warning:

```
/home/mathias/quda/lib/pgauge_det_trace.cu: In function ‘double2 quda::computeValue(quda::cudaGaugeField&) [with Float = float; int functiontype = 0; double2 = double2]’:
/home/mathias/quda/lib/pgauge_det_trace.cu:198:1: warning: control reaches end of non-void function [-Wreturn-type]
```

**Comment by maddyscientist** [comment]
The warnings are all harmless. I actually fixed these already in the feature/multigrid branch (and a tonne of others.....)

**Comment by mathiaswagner** [comment]
You are really trying to force me to approve your pull request for MG whenever it comes by adding in a lot of goodies.
But seriously: Fixing these general things in the MG branch doesn't seem to be best practice. Can we try to fix them in hot fix branches that go into develop and then the can propagate to the feature branches.

**Comment by maddyscientist** [comment]
Absolutely.

In this case I was tracking down a bug, so I ramped up the warnings verbosity but there were so many I had to fix them to be able to parse it.

**Pull request merged**
