### PR TITLE
Iterate until breakdown with mixed precision multi shift

### PR DESCRIPTION
**Pull request by mathiaswagner**
MILC does not stop higher shifts in the multi shift CG solver. They are iterated until zeta becomes zero or the 0th shift converges.
This increases the precision of the higher shifts beyond the specified tolerance.

This could not be mimicked with the mixed precision multi shift solver (with a pure double precision solver quda accepted 0 as residual for the higher shifts and did not use internal refinement for these shifts).
Quda now accepts 0 as tolerance for higher shifts when using mixed precision. The higher shifts are then refined to the iterated residual from the multi shift solve or until the precision is maxed out (10^(-2*cuda_prec+1), e.g.. 1e-15 for double precision.

### CODE REVIEW

**Comment by mikeaclark** [comment]
If uses this will mean our recent pull request to MILC will conflict with this.  If we merge this, we will need to update that pull request (which hasn't been merged yet).  Let me check how well this works with the Cineca benchmarks.

**Comment by mathiaswagner** [comment]
Yes, this will interfere with the pull request to MILC. I guess nothing will be broken but the 'refine until breakdown` won't be used. Refinement will only be up to the residual passed from MILC then.

**Comment by mathiaswagner** [comment]
From my RHMC test using MILC I got:

```
pure double(18): delta S = 3.353277e-01
pure double(9): delta S = 3.353276e-01
double(18)-single(9): delta S = 3.353274e-01
```

Timings (Total time for multi shift):
```
pure double(18): invertMultiShiftQuda Total time = 507.649 secs
pure double(9): invertMultiShiftQuda Total time = 517.512 secs
double(18)-single(9): invertMultiShiftQuda Total time = 840.386 secs
```

While the delta S looks fine to me, refinement is really killing the performance here.

**Comment by mikeaclark** [comment]
This is where double-half refinement and minimum residual extrapolation would really help.

**Comment by mathiaswagner** [comment]
Yes, going step after step here. I just checked iteration counts and to give you an idea (of the current status):
```
MultiShift CG: Converged after 7108 iterations
```
and the refinement for that:

```
Convergence at 5202 iterations, L2 relative residual: iterated = 8.143435e-14, true = 8.143435e-14
Convergence at 4129 iterations, L2 relative residual: iterated = 5.413770e-14, true = 5.413770e-14
Convergence at 3062 iterations, L2 relative residual: iterated = 3.350782e-14, true = 3.350782e-14
Convergence at 2187 iterations, L2 relative residual: iterated = 2.003336e-14, true = 2.003336e-14
Convergence at 1558 iterations, L2 relative residual: iterated = 1.170264e-14, true = 1.170264e-14
Convergence at 1104 iterations, L2 relative residual: iterated = 6.756058e-15, true = 6.756058e-15
Convergence at 791 iterations, L2 relative residual: iterated = 3.907711e-15, true = 3.907711e-15
Convergence at 571 iterations, L2 relative residual: iterated = 2.294070e-15, true = 2.294070e-15
Convergence at 653 iterations, L2 relative residual: iterated = 1.394528e-15, true = 1.394528e-15
Convergence at 548 iterations, L2 relative residual: iterated = 9.500796e-16, true = 9.500796e-16
Convergence at 361 iterations, L2 relative residual: iterated = 7.099076e-16, true = 7.099076e-16
Convergence at 309 iterations, L2 relative residual: iterated = 5.864934e-16, true = 5.864934e-16
Convergence at 298 iterations, L2 relative residual: iterated = 5.299479e-16, true = 5.299479e-16
```

**Pull request merged**
