### PR TITLE
Release 1.0.1

### PR DESCRIPTION
**Pull request by weinbe2**
This PR includes a handful of bugfixes and stability fixes for the 1.0.x release of QUDA, which exists to provide functional (at best) support for older GPUs (Kepler, Maxwell) and still supports versions of CUDA as old as 7.5 if needed for various legacy reasons. This version of the code still contains support for textures. This version of the code is not intended to be used on any modern machine or architecture.

Various build instructions, as well as git commit for compatible versions of MILC, are documented here: https://github.com/lattice/quda/wiki/MILC-with-QUDA#compiling-milc-with-the-quda-10x-release-branch

### CODE REVIEW

**Comment by mathiaswagner** [comment]
@weinbe2 Are the qio updates exact copies from the 1.1.x branch? Ie. the `layout_hyper` and `qio_field` files?

**Comment by weinbe2** [comment]
@mathiaswagner very close, yes, but there were enough annoying deviations that I didn't just `cherry pick` iirc

**Comment by mathiaswagner** [comment]
Thanks. I am just thinking about what kind / level of review and testing will be necessary here.

**Comment by weinbe2** [comment]
I think this should largely be driven by testing with (appropriately old) versions of applications---this exists purely to get `release/1.0.x` compiling and _usable_ again as opposed to much else.

**Review by mathiaswagner — APPROVED** [review]

**Comment by mathiaswagner** [comment]
@Jenkins test this please

**Comment by mathiaswagner** [comment]
The clang as CUDA compiler build fails but we can ignore that.

**Pull request merged**
