### PR TITLE
Feature/gauge comms cleanup

### PR DESCRIPTION
**Pull request by maddyscientist**
(This pull requires that first #642 is merged)

This pull request mainly addresses the enablement of peer-to-peer communication and GPU Direct RDMA for the extended gauge field exchange.
* Move common communications functionality from `ColorSpinorField` into `LatticeField`
* Add support for peer-to-peer and RDMA exchange for extended gauge field creation
* Remove legacy `FaceBuffer` class
* Remove legacy `bufferPinned` and `bufferDevice` static allocations
* Use the clover matrix element symmetry to reduce memory traffic in asymmetric clover dslash
* Remove clover_rho.cu (which added a `rho` constant to the clover diagonal) and replace this functionality with simply adding `rho` to the diagonal when apply clover dslash
* Optimize long-link computation
* Add Fortran helper interface for pinning externally declared memory
* When using BQCD gauge fields, use a hash comparison to check if gauge field needs to be refreshed 
* Ancillary cleanup and optimization

### CODE REVIEW

**Comment by mathiaswagner** [comment]
After merging #642 I merged develop into this (without conflicts) to get a cleaner diff.

**Comment by mathiaswagner** [comment]
Just a question: What is the rationale behind having the interface function for pinning/register only in Fortran?
Looks good otherwise.

**Comment by maddyscientist** [comment]
@mathiaswagner I exposed an interface for pinning / unpinning memory specifically for BQCD.  BQCD uses persistent memory allocations, and so it makes sense to pin it's copy of the gauge field once it has been allocated.  I initially looked into an approach akin to `qudaAllocatePinned`, `qudaFreePinned` as is done in the C interface, however, this proved to be troublesome due to assigning a Fortran array to a C pointer not being a well-defined operation.  I think in the long term we can remove this, and have QUDA internally pin all buffers that are passed to it (if not already pinned), and only free them when `endQuda` is called.  This would simplify application code (obviously this approach would only be for applications that have persistent memory allocations, and it would be opt in).

Make sense?

**Comment by mathiaswagner** [comment]
Yes, sounds like a good plan.

**Pull request merged**
