### PR TITLE
in loadClover, set solve_pc = true also for QUDA_NORMERR_PC_SOLVE

### PR DESCRIPTION
**Pull request by kostrzewa**
Resubmission of #452 for the release/0.8.x series

### CODE REVIEW

**Comment by mathiaswagner** [comment]
Jenkins: Can one of the admins verify this patch?

**Comment by mathiaswagner** [comment]
Jenkins: Can one of the admins verify this patch?

**Comment by mathiaswagner** [comment]
ok to test

**Comment by mathiaswagner** [comment]
Jenkins ok to test

**Comment by maddyscientist** [comment]
@kostrzewa just to let you know that this fix has now been merged into develop as well now, so you should be to use either branch.

**Pull request merged**
