### PR TITLE
Hotfix/mr solver

### PR DESCRIPTION
**Pull request by mikeaclark**
This fixes a long-standing bug in the MR solver, which led to incorrect convergence in the solver.  Also some minor clean up of tests/invert_test adding support for the `--niter` flag to set the maximum number of solver iterations.

### CODE REVIEW

**Comment by bjoo** [comment]
Hi Guys, 
 I see that this was merged into release/0.7.x, is there a chance of 
merging it into master? Or do hotfixes never go there anymore?
I realize that with the gitflow master will have fewer updates, but I though
bugfixes may make it back in. Or do bugfixes just go to the release/ branches now
(essentially making master stable, but not maybe very useful)

Best, 
 B
> On Sep 15, 2015, at 4:47 AM, Mathias Wagner <notifications@github.com> wrote:
> 
> Merged #363.
> 
> —
> Reply to this email directly or view it on GitHub.
> 

--------------------------------------------------------------------------------------
Dr Balint Joo              High Performance Computational Scientist
Jefferson Lab
12000 Jefferson Ave, Suite 3, MS 12B2, Room F217,
Newport News, VA 23606, USA
Tel: +1-757-269-5339,      Fax: +1-757-269-5427
email: bjoo@jlab.org       
-------------------------------------------------------------------------------------

**Comment by mathiaswagner** [comment]
Release will be merged into master once we release 0.7.2. 

The branch release is used to collect fixes to 0.7.x and master is always the latest released version (0.7.1 currently). 

Hope that explains our strategy. 0.7.2 should be out soon. Kate and I have been just too busy to actually test and release it.

**Comment by bjoo** [comment]
Hi Mathias, 
 Thanks. I see the plan. For now, I will have a go using the release/0.7.x branch to pull in this hotfix.

I guess this will provide a little testing :) I’ll let you all know if I hit any bumps. 

Best, 
 B
> On Sep 18, 2015, at 1:25 PM, Mathias Wagner <notifications@github.com> wrote:
> 
> Release will be merged into master once we release 0.7.2.
> 
> The branch release is used to collect fixes to 0.7.x and master is always the latest released version (0.7.1 currently).
> 
> Hope that explains our strategy. 0.7.2 should be out soon. Kate and I have been just too busy to actually test and release it.
> 
> —
> Reply to this email directly or view it on GitHub.
> 

--------------------------------------------------------------------------------------
Dr Balint Joo              High Performance Computational Scientist
Jefferson Lab
12000 Jefferson Ave, Suite 3, MS 12B2, Room F217,
Newport News, VA 23606, USA
Tel: +1-757-269-5339,      Fax: +1-757-269-5427
email: bjoo@jlab.org       
-------------------------------------------------------------------------------------

**Comment by mikeaclark** [comment]
@bjoo it would be great if you tested this before we release 0.7.2 :)

**Comment by bjoo** [comment]
Had the first run on BlueWaters. Seems to be doing well.

**Comment by mikeaclark** [comment]
Any sign of the solver plateauing like it did before?

**Comment by bjoo** [comment]
> On Sep 23, 2015, at 10:04 AM, mikeaclark <notifications@github.com> wrote:
> 
> Any sign of the solver plateauing like it did before?
> 
> —
> Reply to this email directly or view it on GitHub.
> 

Not so far. I do have one ‘Delta H’ spike in the HMC which suggests there
may have been a place with a very light mode. However, the GCR coped
so far. This stagnation type behavior is sporadic, so I wouldn’t write it off
completely yet, without gathering more stats.

Best, 
 B

--------------------------------------------------------------------------------------
Dr Balint Joo              High Performance Computational Scientist
Jefferson Lab
12000 Jefferson Ave, Suite 3, MS 12B2, Room F217,
Newport News, VA 23606, USA
Tel: +1-757-269-5339,      Fax: +1-757-269-5427
email: bjoo@jlab.org       
-------------------------------------------------------------------------------------

**Comment by mikeaclark** [comment]
Fingers crossed then 😉

**Pull request merged**
