### PR TITLE
Added nvtx wrappers for all MPI calls to enable the profiling of MPI

### PR DESCRIPTION
**Pull request by mikeaclark**
This feature enables MPI API calls to be visualized in the visual profiler as opposed to appearing as empty space in the runtime.  This utilizes the PMPI interface to add NVTX markup before and after each MPI call.  This feature can be enabled using the `--enable-mpi-nvtx` to configure.

Here is an nvvp screenshot from a multi-gpu dslash with nvtx markup disabled.

no-mpi-nvtx

And here is the same test but with nvtx markup enabled.

mpi-nvtx

The wrap.py script from LLNL has been used here to automatically generate this markup, making it easy to add new functions if desired.  The wrap.py script and the input to this script (nvtx.w) are in lib/generate, this creates the lib/nvtx_mpi.c file.  If additional MPI API calls needed to be added, these can be added editing the nvtx.w file and generating a new nvtx_mpi.c file: `make mpi_nvtx`.

### CODE REVIEW

**Comment by mathiaswagner** [comment]
Love it when you implement things before I even remember to write the feature request. Had that on my (personal) list since the blog post.

On May 13, 2015, at 19:51, mikeaclark <notifications@github.com<mailto:notifications@github.com>> wrote:


This feature enables MPI API calls to be visualized in the visual profiler as opposed to appearing as empty space in the runtime. This utilizes the PMPI interface to add NVTX markup before and after each MPI call. This feature can be enabled using the --enable-mpi-nvtx to configure.

Here is an nvvp screenshot from a multi-gpu dslash with nvtx markup disabled.

[no-mpi-nvtx]<https://raw.githubusercontent.com/lattice/lattice.github.com/master/results/nvvp_no_nvtx_mpi.png>

And here is the same test but with nvtx markup enabled.

[mpi-nvtx]<https://raw.githubusercontent.com/lattice/lattice.github.com/master/results/nvvp_nvtx_mpi.png>

The wrap.py script from LLNL has been used here to automatically generate this markup, making it easy to add new functions if desired. The wrap.py script and the input to this script (nvtx.w) are in lib/generate, this creates the lib/nvtx_mpi.c file. If additional MPI API calls needed to be added, these can be added editing the nvtx.w file and generating a new nvtx_mpi.c file: make mpi_nvtx.

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/lattice/quda/pull/239

Commit Summary

  *   Added nvtx wrappers for all MPI calls to enable the visual profiler to display MPI timeline information.

File Changes

  *   M LICENSE<https://github.com/lattice/quda/pull/239/files#diff-0> (66)
  *   M Makefile<https://github.com/lattice/quda/pull/239/files#diff-1> (3)
  *   M configure<https://github.com/lattice/quda/pull/239/files#diff-2> (25)
  *   M configure.ac<https://github.com/lattice/quda/pull/239/files#diff-3> (18)
  *   M lib/Makefile<https://github.com/lattice/quda/pull/239/files#diff-4> (3)
  *   A lib/generate/nvtx.w<https://github.com/lattice/quda/pull/239/files#diff-5> (31)
  *   A lib/generate/wrap.py<https://github.com/lattice/quda/pull/239/files#diff-6> (1312)
  *   A lib/nvtx_pmpi.c<https://github.com/lattice/quda/pull/239/files#diff-7> (558)
  *   M make.inc.in<https://github.com/lattice/quda/pull/239/files#diff-8> (8)

Patch Links:

  *   https://github.com/lattice/quda/pull/239.patch
  *   https://github.com/lattice/quda/pull/239.diff

**Comment by mathiaswagner** [comment]
I saw some 'previously defined here' errors when trying a parallel build. I am trying a serial build now. Anyhow and will try the parallel build again after that. Anyhow, not being able to build quda in parallel is a pain. Especially for a development feature when you might be building quite often.

Has anyone else seen issues when trying a parallel build (`make -j`) ?

**Comment by mikeaclark** [comment]
I haven't seen this (I always build in parallel). What is it complaining about?
-----------------------------------------------------------------------------------
This email message is for the sole use of the intended recipient(s) and may contain
confidential information.  Any unauthorized review, use, disclosure or distribution
is prohibited.  If you are not the intended recipient, please contact the sender by
reply email and destroy all copies of the original message.
-----------------------------------------------------------------------------------

**Comment by mathiaswagner** [comment]
Some pasted output:
```
mpicc			 -Wall -O3 -std=c99 -D__COMPUTE_CAPABILITY__=350 -DMULTI_GPU -DGPU_WILSON_DIRAC -DGPU_DOMAIN_WALL_DIRAC -DGPU_STAGGERED_DIRAC -DGPU_CLOVER_DIRAC -DGPU_WILSON_DIRAC -DGPU_GAUGE_TOOLS -DGPU_TWISTED_MASS_DIRAC -DGPU_WILSON_DIRAC -DGPU_DIRECT -DBUILD_QDP_INTERFACE -DBUILD_MILC_INTERFACE -DNUMA_AFFINITY -I/usr/local/cuda-7.0//include -DMPI_COMMS  -I/usr/mpi/gcc/openmpi-1.4.1//include -I../include -Idslash_core -I.   -c -o nvtx_pmpi.o nvtx_pmpi.c
nvtx_pmpi.c:55: error: conflicting types for ‘PMPI_Send’
/usr/mpi/gcc/openmpi-1.4.1/include/mpi.h:1717: error: previous declaration of ‘PMPI_Send’ was here
nvtx_pmpi.c:56: error: conflicting types for ‘MPI_Send’
/usr/mpi/gcc/openmpi-1.4.1/include/mpi.h:1207: error: previous declaration of ‘MPI_Send’ was here
nvtx_pmpi.c:97: error: conflicting types for ‘PMPI_Allreduce’
/usr/mpi/gcc/openmpi-1.4.1/include/mpi.h:1383: error: previous declaration of ‘PMPI_Allreduce’ was here
nvtx_pmpi.c:98: error: conflicting types for ‘MPI_Allreduce’
/usr/mpi/gcc/openmpi-1.4.1/include/mpi.h:875: error: previous declaration of ‘MPI_Allreduce’ was here
nvtx_pmpi.c:118: error: conflicting types for ‘PMPI_Reduce’
/usr/mpi/gcc/openmpi-1.4.1/include/mpi.h:1687: error: previous declaration of ‘PMPI_Reduce’ was here
nvtx_pmpi.c:119: error: conflicting types for ‘MPI_Reduce’
/usr/mpi/gcc/openmpi-1.4.1/include/mpi.h:1177: error: previous declaration of ‘MPI_Reduce’ was here
nvtx_pmpi.c:223: error: conflicting types for ‘PMPI_Gather’
/usr/mpi/gcc/openmpi-1.4.1/include/mpi.h:1568: error: previous declaration of ‘PMPI_Gather’ was here
nvtx_pmpi.c:224: error: conflicting types for ‘MPI_Gather’
/usr/mpi/gcc/openmpi-1.4.1/include/mpi.h:1060: error: previous declaration of ‘MPI_Gather’ was here
nvtx_pmpi.c:244: error: conflicting types for ‘PMPI_Gatherv’
/usr/mpi/gcc/openmpi-1.4.1/include/mpi.h:1571: error: previous declaration of ‘PMPI_Gatherv’ was here
nvtx_pmpi.c:245: error: conflicting types for ‘MPI_Gatherv’
/usr/mpi/gcc/openmpi-1.4.1/include/mpi.h:1063: error: previous declaration of ‘MPI_Gatherv’ was here
nvtx_pmpi.c:265: error: conflicting types for ‘PMPI_Scatter’
/usr/mpi/gcc/openmpi-1.4.1/include/mpi.h:1709: error: previous declaration of ‘PMPI_Scatter’ was here
nvtx_pmpi.c:266: error: conflicting types for ‘MPI_Scatter’
```

I am waiting for my serial build to finish and will then try again in parallel. Maybe my build directory wasn't  properly cleaned.

**Comment by mikeaclark** [comment]
I see you're using an old MPI version, I wonder if this could be the problem (PMPI support needed). Also I've only tested it with MVAPICH and not OpenMPI.
-----------------------------------------------------------------------------------
This email message is for the sole use of the intended recipient(s) and may contain
confidential information.  Any unauthorized review, use, disclosure or distribution
is prohibited.  If you are not the intended recipient, please contact the sender by
reply email and destroy all copies of the original message.
-----------------------------------------------------------------------------------

**Comment by mathiaswagner** [comment]
That might be. It is the local development machine which is pretty outdated. 
I'll also give it a try on the local cray.

**Comment by mathiaswagner** [comment]
Another thing that cam to my mind: What happens when we use QMP? 
Will the option have any effect then?

**Comment by mathiaswagner** [comment]
Guess you are right about the old MPI. Anyway, build still works without NVTX.
The build on the cray seems to do fine.

**Comment by mathiaswagner** [comment]
My first try on the cray triggered an internal profiler error - but I only have CUDA 5.5 available there.
I don't consider this to be an issue with this feature in general. 

And I really do like this feature. Might we also be able to print the time spend in communication the summary output?

**Comment by mikeaclark** [comment]
This should work fine with QMP: since QMP calls MPI underneath (at least when running on QUDA).

Cray should be in the process of updating all XK7 machines to CUDA 6.5, so this local issue you're having should be rectified soon.

**Comment by mathiaswagner** [comment]
I know. I was actually running CUDA 6.5 tests on blue waters.
I just wanted to comment that I could not actually (easily) use it on any of _my_ local machines.

**Comment by mikeaclark** [comment]
I've just confirmed that it works fine with OpenMPI 1.8.2, so the issues you saw Mathias were likely due to the age of OpenMPI.

**Comment by mathiaswagner** [comment]
Thanks.

**Pull request merged**
