### PR TITLE
Feature/multigrid circlestag

### PR DESCRIPTION
**Pull request by weinbe2**
This incremental pull request adds support for using the translation-invariant null vector for the Wilson free field operator. The coarsened free field Wilson operator has Nc = 6 (times 2 for coarse spin equals the 12 DoF per site on the fine level), which requires templating over a whole slew of additional Nc values throughout the code. This gets expensive, so I added an advanced CMake flag, QUDA_MULTIGRID_FREEFIELD_TEMPLATE (default off) that when switched on templates over the additionally required Ncolor. Make sure to set this to "ON" for the compile before testing!

This has been tested both for a 2 level and 3 level algorithm (the three level requires still additional templating for coarsening an Nc = 6 op to an Nc = 6 op). This has only been tested with --mg-solver-type direct-pc, since for reasons I can't understand --mg-solver-type direct doesn't work (it complains about needing a preconditioned smoother solve, which I couldn't figure out a way around...). This has been tested both single GPU and emulated multi GPU (which required a bit of extra templating for ghost packing routines). This has been tested against the Wilson, Wilson-clover (uninteresting in free field), twisted mass, and twisted clover operator.

The free field case is triggered in the test routines by specifying "--mg-generate-nullspace false" without supplying null vectors to load via "--mg-load-vec [file]", which seemed reasonable, but I can come up with something a bit more natural if necessary. I updated the output of the "--help" flag appropriately.

Example invocation of a three level Wilson solve:

`./multigrid_invert_test --prec double --prec-sloppy single --mg-levels 3 --mg-block-size 0 3 3 3 2 --mg-block-size 1 2 2 2 2 --solve-type direct-pc --dslash-type wilson --device 1 --mg-generate-nullspace false --mg-nvec 0 6 --mg-nvec 1 6 --mass 0.00001 --mg-coarse-solver-maxiter 1 100 --mg-coarse-solver-maxiter 2 100`

Example invocation of a two level twisted mass solve:

`./multigrid_invert_test --prec double --prec-sloppy single --mg-levels 2 --mg-block-size 0 3 3 3 2 --solve-type direct-pc --dslash-type twisted-mass --device 1 --mg-generate-nullspace false --mg-nvec 0 6 --mass 0.1 --mg-coarse-solver-maxiter 1 100`

Along the way, I started hitting "verify" issues after merging in feature/multigrid. After doing some runs with Nc = 24, I found that I could reproduce these issues exactly in feature/multigrid, which means the issue was introduced in that branch along the way and not while adding free field values. I'll be submitting an issue for that subsequently. In any case, it isn't reflective of an issue with this pull request.

### CODE REVIEW

**Comment by mathiaswagner** [comment]
Jenkins: Can one of the admins verify this patch?

**Comment by mathiaswagner** [comment]
Jenkins: Can one of the admins verify this patch?

**Comment by mathiaswagner** [comment]
Jenkins: Can one of the admins verify this patch?

**Comment by weinbe2** [comment]
Ah, I missed that you had a very, very recent push to feature/multigrid. Let me check that.

**Comment by weinbe2** [comment]
@maddyscientist I correct that---it looks like I have the latest version of feature/multigrid merged in, unless I made a mistake. 

https://github.com/lattice/quda/compare/feature/multigrid...feature/multigrid-circlestag

**Comment by mathiaswagner** [comment]
Is this for 0.9.0?

**Comment by maddyscientist** [comment]
@mathiaswagner no, this is just a pull into feature/multigrid, and that branch will not be going into 0.9.0

**Comment by mathiaswagner** [comment]
Missed that on the mobile version of GitHub...

**Comment by mathiaswagner** [comment]
Jenkins: Can one of the admins verify this patch?

**Comment by weinbe2** [comment]
As an fyi these latest pushes in no way mean this pull request is ready to be approved, but they're going in the right direction.

**Comment by weinbe2** [comment]
@maddyscientist With your latest fixes, this merge is ready to go so far as my tests have indicated. I tried wilson, clover, twisted-mass, twisted-clover at various volumes and emulated partitionings and didn't hit any issues. I also made sure I didn't accidentally break a "regular" test of an MG run where 24/32 null vectors are generated. The example commands from my original pull request are still valid ways to test it, if you're interested.

**Comment by mathiaswagner** [comment]
Jenkins: Can one of the admins verify this patch?

**Comment by mathiaswagner** [comment]
Jenkins: Can one of the admins verify this patch?

**Comment by mathiaswagner** [comment]
Jenkins: Can one of the admins verify this patch?

**Pull request merged**
