### PR TITLE
Hotfix/hisq fermion force

### LINKED ISSUE #622: tuning problem on SummitDev
I am finally getting back to SummitDev and able to launch multiple GPU job using the develop branch of QUDA.  However, I am running into a problem.  Here is how a typical job ends:

CONGRAD5: time = 2.279687e-02 (multicg_offset_QUDA D) masses = 7 iters = 35 mflops = 8.238043e+03
 OK converged final_rsq= 6.6e-27 (cf 2.5e-17) rel = 1.2e-24 (cf 0) restarts = 0 iters= 35
ERROR: Failed to clear error state an illegal memory access was encountered
 (rank 0, host summitdev-r0c0n14, /ccs/home/gottlieb/quda/lib/tune.cpp:615 in tuneLaunch())
       last kernel called was (name=N4quda17PackFaceStaggeredI7double2dEE,volume=4x8x8x8,aux=vol=2048,stride=2048,precision=8,Ns=1,Nc=3,comm=0011,nFace=3,location=)
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------

The job launch commands look like this:
   mpirun -MXM -n $nodes --hostfile $LSB_DJOB_HOSTFILE --bind-to core --map-by ppr:2:socket ./$EXE <params${nodes}.$ns  >out_np$nodes.$ns.pretune
   mpirun -MXM -n $nodes --hostfile $LSB_DJOB_HOSTFILE --bind-to core --map-by ppr:2:socket ./$EXE <params${nodes}.$ns  >out_np$nodes.$ns

There is a tune file and a non-empty file tunecache.tsv.  I searched for the name of the last kernel called in the tunecache.csv file and this is what I find:

grep N4quda17PackFaceStaggered tunecache.tsv
   10x20x20x20x1        N4quda17PackFaceStaggeredI7double2dEE   vol=80000,stride=80000,precision=8,Ns=1,Nc=3,comm=0011,kernelPackT,nFace=3,location=  480     1       1       100     1       1       1638511       1       1       5.5264e-05      # 0.00 Gflop/s, 83.38 GB/s, tuned Sun Jun 11 16:16:31 2017
   10x20x20x20x1        N4quda17PackFaceStaggeredI7double2dEE   vol=80000,stride=80000,precision=8,Ns=1,Nc=3,comm=0011,nFace=3,location=      448     1       1       54      1       1       16385   1    11       1       8.56533e-06     # 0.00 Gflop/s, 268.99 GB/s, tuned Sun Jun 11 16:16:31 2017
   12x24x24x24x1        N4quda17PackFaceStaggeredI7double2dEE   vol=165888,stride=165888,precision=8,Ns=1,Nc=3,comm=0011,kernelPackT,nFace=3,location=        864     1       1       96      1       1    01       1       1       1       9.26293e-05     # 0.00 Gflop/s, 85.96 GB/s, tuned Sun Jun 11 16:17:42 2017
   12x24x24x24x1        N4quda17PackFaceStaggeredI7double2dEE   vol=165888,stride=165888,precision=8,Ns=1,Nc=3,comm=0011,nFace=3,location=    256     1       1       162     1       1       9831    1    11       1       9.30133e-06     # 0.00 Gflop/s, 428.04 GB/s, tuned Sun Jun 11 16:17:42 2017
   14x28x28x28x1        N4quda17PackFaceStaggeredI7double2dEE   vol=307328,stride=307328,precision=8,Ns=1,Nc=3,comm=0011,kernelPackT,nFace=3,location=        608     1       1       217     1       1    24577    1       1       1       1       0.000144736     # 0.00 Gflop/s, 87.36 GB/s, tuned Sun Jun 11 16:19:50 2017
   14x28x28x28x1        N4quda17PackFaceStaggeredI7double2dEE   vol=307328,stride=307328,precision=8,Ns=1,Nc=3,comm=0011,nFace=3,location=    480     1       1       138     1       1       12289   1    11       1       1.56373e-05     # 0.00 Gflop/s, 404.30 GB/s, tuned Sun Jun 11 16:19:50 2017
   16x32x32x32x1        N4quda17PackFaceStaggeredI7double2dEE   vol=524288,stride=524288,precision=8,Ns=1,Nc=3,comm=0011,kernelPackT,nFace=3,location=        640     1       1       308     1       1    01       1       1       1       0.00021376      # 0.00 Gflop/s, 88.30 GB/s, tuned Sun Jun 11 16:23:35 2017
   16x32x32x32x1        N4quda17PackFaceStaggeredI7double2dEE   vol=524288,stride=524288,precision=8,Ns=1,Nc=3,comm=0011,nFace=3,location=    352     1       1       280     1       1       9831    1    11       1       2.29653e-05     # 0.00 Gflop/s, 410.93 GB/s, tuned Sun Jun 11 16:23:34 2017
       4x8x8x8x1        N4quda17PackFaceStaggeredI7double2dEE   vol=2048,stride=2048,precision=8,Ns=1,Nc=3,comm=0011,kernelPackT,nFace=3,location=    64      1       1       48      1       1       1228911       1       1       9.54667e-06     # 0.00 Gflop/s, 30.89 GB/s, tuned Sun Jun 11 16:15:13 2017
       4x8x8x8x1        N4quda17PackFaceStaggeredI7double2dEE   vol=2048,stride=2048,precision=8,Ns=1,Nc=3,comm=0011,nFace=3,location=        32      1       1       48      1       1       8193    1    11       1       8.672e-06       # 0.00 Gflop/s, 17.00 GB/s, tuned Sun Jun 11 16:15:12 2017
    6x12x12x12x1        N4quda17PackFaceStaggeredI7double2dEE   vol=10368,stride=10368,precision=8,Ns=1,Nc=3,comm=0011,kernelPackT,nFace=3,location=  96      1       1       108     1       1       1638511       1       1       1.6608e-05      # 0.00 Gflop/s, 59.93 GB/s, tuned Sun Jun 11 16:15:29 2017
    6x12x12x12x1        N4quda17PackFaceStaggeredI7double2dEE   vol=10368,stride=10368,precision=8,Ns=1,Nc=3,comm=0011,nFace=3,location=      192     1       1       27      1       1       6145    1    11       1       9.696e-06       # 0.00 Gflop/s, 51.33 GB/s, tuned Sun Jun 11 16:15:29 2017
    8x16x16x16x1        N4quda17PackFaceStaggeredI7double2dEE   vol=32768,stride=32768,precision=8,Ns=1,Nc=3,comm=0011,kernelPackT,nFace=3,location=  288     1       1       86      1       1       8193 11       1       1       3.1072e-05      # 0.00 Gflop/s, 75.93 GB/s, tuned Sun Jun 11 16:15:51 2017
    8x16x16x16x1        N4quda17PackFaceStaggeredI7double2dEE   vol=32768,stride=32768,precision=8,Ns=1,Nc=3,comm=0011,nFace=3,location=      256     1       1       48      1       1       16385   1    11       1       8.29867e-06     # 0.00 Gflop/s, 142.15 GB/s, tuned Sun Jun 11 16:15:50 2017

Would be happy to send any more desired information to diagnose this issue.

### PR DESCRIPTION
**Pull request by maddyscientist**
This pull request cleans up some old code, improves robustness and fixes a few issues in the HISQ fermion force (closes #622)
* Removes legacy staggered outer product code, replaces it with the (formerly) experimental variant which is now generalized for both nFace=1 and nFace=3 cases
* Fix for nFace setting in fermion force and improved robustness to catch undefined behaviour in this regard
* Fix for small-volume quark fields that are references to non-native fields (do not apply alignment) 
* Fix for CPU quark-field even/odd subsets, when the parent field is itself a reference field
* Removes legacy interface functions that are no longer used

@stevengottlieb I have verified that the develop branch of MILC works without issue with this, and I get results that match both QUDA 0.8 and MILC without any GPU acceleration.  If you have a chance to test this also, that would be great.

### CODE REVIEW

**Comment by mathiaswagner** [comment]
Link step seems to fail with:
```
CMakeFiles/quda.dir/quda_generated_clover_outer_product.cu.o: In function `quda::coordsFromIndex(int*, unsigned int, int const*, unsigned int, int, unsigned int)':
tmpxft_0000246f_00000000-4_clover_outer_product.cudafe1.cpp:(.text+0x120): multiple definition of `quda::coordsFromIndex(int*, unsigned int, int const*, unsigned int, int, unsigned int)'
CMakeFiles/quda.dir/quda_generated_staggered_oprod.cu.o:tmpxft_00001f48_00000000-4_staggered_oprod.cudafe1.cpp:(.text+0x20): first defined here
```

Any ideas of the performance impact?

**Comment by maddyscientist** [comment]
That's weird, it's linking fine here.  Just did a clean build to make sure.

**Comment by maddyscientist** [comment]
To answer your question, there should be minimal performance impact.

**Comment by mathiaswagner** [comment]
Quick diff shows code duplication for CoordsFromIndex. We should pull that in a shared header. The issue seems to be a missing `static` for the CoordsFromIndex for the exterior kernels. The link issue will only show up if staggered and clover dirac are enabled.

**Comment by maddyscientist** [comment]
I've pushed a fix (added static declarations).  Note the intention is to further clean up this code in the soon-to-come™ HISQ force rewrite.  Indeed, all indexing routines in general should be in index_helper.cuh.

**Comment by mathiaswagner** [comment]
What is stopping us from pulling the shared indexing thing out now-is-better-than-soon™?

**Comment by maddyscientist** [comment]
This code is going to get completely rewritten, and the indexing routines will be changed.

Anyway, this is supposed to be a hotfix branch not a feature branch 😄

**Comment by mathiaswagner** [comment]
Would have probably never complained of the build had not failed in the first place. 
I am waiting for @stevengottlieb to comment on whether he has cycles to run a test before merging.

**Comment by stevengottlieb** [comment]
Do you just want me to run a test of the hotfix/hisq fermion force
branch to see if it giving same results as before in rhmc code?

**Comment by mathiaswagner** [comment]
@stevengottlieb: Yes, that would be a very useful data point.

**Comment by maddyscientist** [comment]
Just to note that I've been able to run the APEX benchmarks without issue on Piz Daint now.

**Comment by mathiaswagner** [comment]
@stevengottlieb Just wanted to follow up here and check whether you had a chance to run this branch.

**Comment by stevengottlieb** [comment]
Unfortunately, I spent all week packing up my office for move to the
newly renovated part of the building.  Laura and I finished the packing
last night at midnight.  I am sitting in my bare office with just the
furniture, a few boxes, and denali waiting for the movers to arrive and
complete the transfer.

Very sorry for the delay.  I hope to be able to start testing on Big Red
2 later today.

Steve

**Comment by mathiaswagner** [comment]
No worries. This is not particularly urgent. I can imagine that packing up your office took some time. I am just checking the open pull request from time to time.

**Comment by mathiaswagner** [comment]
Merging now as I did not hear about any issues so far.

**Pull request merged**
