### PR TITLE
Initialization of madwf_param_infile and madwf_param_outfile

### PR DESCRIPTION
**Pull request by Marcogarofalo**
co-author: [sunpho84](https://github.com/sunpho84)
this should fix the issue https://github.com/sunpho84/quda/issues/1

### CODE REVIEW

**Comment by hummingtree** [comment]
Thanks for catching this. I have a more comprehensive fix of the issue in #1248. Can you please check and see if that addresses your issue?

**Comment by Marcogarofalo** [comment]
Thank you for the reply. I was not sure if this part should be compatible with c.

**Comment by hummingtree** [comment]
> Thank you for the reply. I was not sure if this part should be compatible with c.

Not sure you mean which part? All QUDA internals are C++ while the interface is C-compatible.

**Comment by Marcogarofalo** [comment]
if this structure MadwfParam appears in the interface.

**Comment by hummingtree** [comment]
> if this structure MadwfParam appears in the interface.

`MadwfParam` does not appear in the interface, i.e. it is internal.

**Comment by hummingtree** [comment]
@Marcogarofalo Now that #1248 has been merged, can you check and close this one? Thanks.

**Comment by Marcogarofalo** [comment]
sure thank you.

**Pull request closed without merging**
