### PR TITLE
Fixed bug in clover inversion

### PR DESCRIPTION
**Pull request by maddyscientist**
Introduced with commit 38fda505cc1aec25c9c351ad8a093a5c2fcf8f0b.

@AlexVaq Can you merge and close this please?

### CODE REVIEW

**Comment by AlexVaq** [comment]
> @AlexVaq <https://github.com/AlexVaq> Can you merge and close this please?
> 


Ok, let me have a look.

**Comment by AlexVaq** [comment]
Ok, I see. With the new accessor you were reading out of bounds. Most likely we would get garbage for the clover.

Looks correct now. I'll run a fast check and merge unless something goes really wrong.

**Comment by maddyscientist** [comment]
Yep.  I've checked with a clover RHMC run, and it seems to be fine now.

**Comment by AlexVaq** [comment]
It fails dslash_test 0, 1 and 3 with DYNAMIC_CLOVER. I’m trying to find out whether this is because the problem has not been fixed for the dynamic inversion or because the host routines failed unexpectedly.

I’m running without DYNAMIC_CLOVER, I’ll review the code for the inversion on-the-fly and let you know.

**Comment by AlexVaq** [comment]
Removing DYNAMIC_CLOVER fixes it. Definitely there is a problem with the inversion on-the-fly. Looking into that now.

**Comment by AlexVaq** [comment]
I'll have to check multigrid dynamic clover, so this might take long...

**Comment by AlexVaq** [comment]
I believe the flaw lies in the test routine, that wrongly copies back the inverse clover term for the dynamic inversion. This would be good news, because the gpu implementation would be correct, but I want to ensure everything is right and the only way to do that is to fix this copy-back.

**Comment by AlexVaq** [comment]
It seems the problem was in dslash_test.cpp: the inverse clover was not copied back to the CPU in the case of dynamic clover inversion. I added a fix, but before merging I'd like to do further testing.

**Comment by AlexVaq** [comment]
Ok, in the end I think that single line does the job. @maddyscientist do you want to review this or should I go on with the merging? I passed dslash_test, invert_test and multigrid_invert_test, so I guess it's safe.

**Comment by AlexVaq** [comment]
Merged #483.

**Comment by maddyscientist** [comment]
@AlexVaq Thanks for fixing that last dslash_test bug.  I presume that regular clover continued to work ok?

When I have time I will plan on adding dynamic-clover support to regular clover as well to fully merge the clover twisted-clover paths.  At the same time I'll probably also make dynamic-clover a run-time policy rather than compile time, as it will make it easier to test.

**Comment by AlexVaq** [comment]
Yes, clover is working as before. I didn't try clover multigrid, but I don't see how this should be affected.

A merging of paths would be very useful, it would simplify maintenance. And yes, the dynamic inversion should be selected at runtime.

**Pull request merged**
