### PR TITLE
add optional ability to install QUDA tests

### PR DESCRIPTION
**Pull request by mathiaswagner**
This add an option ability (controlled by QUDA_INSTALL_ALL_TESTS) to have the install target also install the QUDA tests.

Currently we only supported installation of the library and headers.

### CODE REVIEW

**Comment by mathiaswagner** [comment]
Seems I need to fix this for older cmake version ...

**Comment by mathiaswagner** [comment]
This should wait on #974 to avoid conflicts. Once #974 has been merged I'll updated it here.

**Comment by mathiaswagner** [comment]
This now requires #974 to be merged first.

**Comment by mathiaswagner** [comment]
I think this is good now. It gets rid of some of the `cuda_` prefixed versions in the CMakeLists.

**Review by maddyscientist — APPROVED** [review]
This looks good to me, but I wasn't asked to review it.  😉 We can hold off merging until at least one of @cpviolator or @weinbe2 give the go ahead.  In particular, I would like to have confirmation that all works on Summit ok (or did you test this already @mathiaswagner ? )

**Comment by cpviolator** [comment]
I'll spin this up on summit right now.

**Comment by cpviolator** [comment]
This installed fine, but one thing cropped up I should mention. The CMAKE default value for the install lib dir is `lib64` but the installation created a directory called `lib`. I was also advised by the installation to:
```
-- Set runtime path of "/ccs/proj/lgt104/howarth/install/bin/plaq_test" to "/ccs/proj/lgt104/howarth/install/lib64"
-- Installing: /ccs/proj/lgt104/howarth/install/bin/su3_test
-- Set runtime path of "/ccs/proj/lgt104/howarth/install/bin/su3_test" to "/ccs/proj/lgt104/howarth/install/lib64"
-- Installing: /ccs/proj/lgt104/howarth/install/bin/pack_test
-- Set runtime path of "/ccs/proj/lgt104/howarth/install/bin/pack_test" to "/ccs/proj/lgt104/howarth/install/lib64"
```
which would definitely lead to an error.

**Comment by cpviolator** [comment]
After my last commit, the the following error is thrown when CMake in invoked:
```
CMake Error at lib/CMakeLists.txt:254 (install):
   install FILES given no DESTINATION!

 CMake Error at lib/CMakeLists.txt:272 (install):
   install DIRECTORY given no DESTINATION!
```
If you ignore it and set CMake variables as usual, it will go on and configure without issue.

**Comment by cpviolator** [comment]
Using the following CMake variable:
```CMAKE_INSTALL_BINDIR             bin_custom                                                                                                                                     
 CMAKE_INSTALL_DATADIR                                                                                                                                                           
 CMAKE_INSTALL_DATAROOTDIR        share                                                                                                                                          
 CMAKE_INSTALL_DOCDIR                                                                                                                                                            
 CMAKE_INSTALL_INCLUDEDIR         include_custom                                                                                                                                 
 CMAKE_INSTALL_INFODIR                                                                                                                                                           
 CMAKE_INSTALL_LIBDIR             lib64_custom                                                                                                                                   
 CMAKE_INSTALL_LIBEXECDIR         libexec                                                                                                                                        
 CMAKE_INSTALL_LOCALEDIR                                                                                                                                                         
 CMAKE_INSTALL_LOCALSTATEDIR      var                                                                                                                                            
 CMAKE_INSTALL_MANDIR                                                                                                                                                            
 CMAKE_INSTALL_OLDINCLUDEDIR      /usr/include                                                                                                                                   
 CMAKE_INSTALL_PREFIX             /ccs/proj/lgt104/howarth/install                                                                                                               
 CMAKE_INSTALL_RUNSTATEDIR                                                                                                                                                       
 CMAKE_INSTALL_SBINDIR            sbin                                                                                                                                           
 CMAKE_INSTALL_SHAREDSTATEDIR     com                                                                                                                                            
 CMAKE_INSTALL_SYSCONFDIR         etc                            
```
on commit https://github.com/lattice/quda/pull/980/commits/03ef5a6ff5639950a78635ab07aea615ce1a6663 the installation directory looks like:
```
howarth@login4:/ccs/proj/lgt104/howarth/quda-cmake-install$ lls ../install/
total 20K
drwxrwxr-x 2 howarth howarth 4.0K May  5 21:05 bin_custom
drwxrwxr-x 3 howarth howarth 4.0K May  5 21:05 lib
drwxr-xr-x 4 howarth howarth 8.0K May  5 21:05 include_custom
drwxrwxr-x 2 howarth howarth 4.0K May  5 21:05 lib64_custom
```
with all the CMake files in `lib` and the actual library in `lib64_custom`.

**Review by cpviolator — APPROVED** [review]
Provided everybody is OK with the loose `lib` dir, all good by me.

**Comment by mathiaswagner** [comment]
I guess the `lib` destination is what was always there. The install target is not used a lot (@bjoo uses it for Chroma packages). If there are any issues in real life we can fix it now but I never heard complaints. I'd say we merge this now and continue improving later (when we overhaul more bits and pieces of the build system)

**Pull request merged**
