### PR TITLE
added missing header file for signal handling, required when HOSTDEBUG option is set

### PR DESCRIPTION
**Pull request by alexstrel**
A minor fix

### CODE REVIEW

**Comment by mathiaswagner** [comment]
Can you elaborate on what was going wrong without the header?

**Comment by alexstrel** [comment]
Compiler emits an error (undefined functions, e.g., raise() that is decorated by HOST_DEBUG). Got this during compilation on Kate's machine.

**Comment by mathiaswagner** [comment]
Thanks. I missed that when moving the `raise` around. I think we can now remove the `signal` header from `comm_single/mpi/qmp.h`

**Comment by alexstrel** [comment]
Done

**Pull request merged**
