### PR TITLE
Hotfix/nface

### LINKED ISSUE #1512: Out of bounds error when running multi-GPU/partitioned HISQ MG with long links dropped
In brief, there is an oob error when running HISQ MG with long links dropped, though it can be triggered without ever dropping to a true coarser level. It only appears with non-zero partitioning; I haven't tested if running it with true multi-GPU is fine or not. There are no issues when "normal" HISQ MG is run (improved staggered on the pseudo-fine level as well), suggesting that something is going awry with switching between the improved staggered (outer level) and unimproved staggered (inner level) operators.

The error does not hit until the first solve, i.e. after setup as completed. It more specifically triggers when returning to the fine level from the pseudo-fine level, aka when going to applying the improved operator from the unimproved operator. The time at which it hits (when it does) depends on the local volume---no error on ~16^4, but it hits on the first iteration on ~24^4+. It does seem to be deterministic at fixed command incl volume, at least.

This error hits independent of if tuning is enabled or not.

A command that triggers it is as follows:
```
mpirun -np 1 ./staggered_invert_test \
  --mass 0.1 \
  --dim 24 24 24 24 --gridsize 1 1 1 1 --partition 8 \
  --dslash-type asqtad --tol 1e-5 \
  --verbosity verbose --solve-type direct --solution-type mat --inv-type gcr \
  --inv-multigrid true --mg-levels 2 --mg-coarse-solve-type 0 direct --mg-staggered-coarsen-type kd-optimized-drop-long \
  --mg-block-size 0 1 1 1 1 --mg-nvec 0 3 \
  --nsrc 1 --niter 25 \
  --mg-smoother 0 ca-gcr --mg-smoother-solve-type 0 direct --mg-nu-pre 0 0 --mg-nu-post 0 8 \
  --mg-smoother 1 ca-gcr --mg-smoother-solve-type 1 direct --mg-nu-pre 1 0 --mg-nu-post 1 8 \
  --mg-coarse-solver 1 gcr --mg-coarse-solve-type 1 direct --mg-coarse-solver-tol 1 0.25 --mg-coarse-solver-maxiter 1 16 \
  --mg-verbosity 0 verbose --mg-verbosity 1 verbose
```

This is roughly trimmed down as much as possible, the various combinations of `mat` and `direct` are non-default but required for HISQ MG as is currently implemented. As noted above you never actually need to enter a true coarse solve to trigger the error, but you do still need to compile with `Nc = 24` for the KD-operator construction.

A representative error message is:
```
QMP m0,n1@viking-prod-259.nvidia.com error: abort: 1
MG level 0 (GPU): ERROR: qudaEventQuery_ returned CUDA_ERROR_ILLEGAL_ADDRESS
 (dslash_policy.hpp:398 in operator()())
 (rank 0, host viking-prod-259.nvidia.com, quda_api.cpp:72 in void quda::target::cuda::set_driver_error(CUresult, const char*, const char*, const char*, const char*, bool)())
MG level 0 (GPU):        last kernel called was (name=N4quda9StaggeredINS_12StaggeredArgIfLi3ELi4EL21QudaReconstructType_s18ELS2_18ELb1EL20QudaStaggeredPhase_s1EEEEE,volume=24x24x24x24,aux=policy_kernel=interior,GPU-offline,vol=331776,parity=2,precision=4,order=2,Ns=1,Nc=3,commDim=0001,xpay,n_rhs=1,comm=0001)
```

My cmake command was:
```
cmake -DQUDA_DIRAC_DEFAULT_OFF=ON \
      -DQUDA_DIRAC_STAGGERED=ON \
      -DCMAKE_BUILD_TYPE=DEVEL \
      -DQUDA_BACKWARDS=ON \
      -D CMAKE_INSTALL_PREFIX=/scratch/local/install \
      -DQUDA_PRECISION=12 \
      -DQUDA_RECONSTRUCT=4 \
      -DQUDA_MPI=ON \
      -DQUDA_FAST_COMPILE_DSLASH=ON \
      -DQUDA_FAST_COMPILE_REDUCE=ON \
      -DQUDA_GPU_ARCH=sm_80 \
      -DQUDA_MULTIGRID=ON \
      -DQUDA_MULTIGRID_NVEC_LIST="24" \
     [quda]
```

### LINKED ISSUE #1513: QUDA's device-side RNG needs to be updated to support global volumes > `2^31 - 1`
As part of initializing QUDA's hypercubic RNG, it needs to compute the _global_ lattice index corresponding to each _local_ site. This is currently accumulated into an `int32`: https://github.com/lattice/quda/blob/develop/include/kernels/random_init.cuh#L49

For sufficiently large global volumes (such as MILC's 192^3x384 configurations) this can overflow leading to identical streams across different global lattice sites. The high-level solution is to promote this value to a uint64, but that will require further changes under the hood.

### PR DESCRIPTION
**Pull request by maddyscientist**
Bug fix PR, with a minor optimization
* Fix 32-bit overflow issue with `init_random`, closes #1513 
* Fix issue with change halo depth, closes #1512
* Use push / pop verbosity in `tuneLaunch` so that `logQuda` respect local verbosity setting
* Used batched calls where possible in `dirac_quda.h`

### CODE REVIEW

**Comment by weinbe2** [comment]
This PR indeed works around the crash in #1512 but there's still a residual issue as the residual goes bonkers when it's explicitly recomputed during the reliable update:

```
> ./run.sh | grep "GCR:    " | grep -v "MG level"
GCR:     0 iterations, <r,r> = 6.636512e+05, |r|/|b| = 1.000000e+00
GCR:     1 iterations, <r,r> = 6.579112e+05, |r|/|b| = 9.956661e-01
GCR:     2 iterations, <r,r> = 6.567184e+05, |r|/|b| = 9.947631e-01
GCR:     3 iterations, <r,r> = 6.561516e+05, |r|/|b| = 9.943337e-01
GCR:     4 iterations, <r,r> = 6.561489e+05, |r|/|b| = 9.943316e-01
GCR:     5 iterations, <r,r> = 6.561489e+05, |r|/|b| = 9.943316e-01
GCR:     6 iterations, <r,r> = 6.561402e+05, |r|/|b| = 9.943251e-01
GCR:     7 iterations, <r,r> = 6.561375e+05, |r|/|b| = 9.943230e-01
GCR:     8 iterations, <r,r> = 6.559700e+05, |r|/|b| = 9.941961e-01
GCR:     9 iterations, <r,r> = 5.471467e+22, |r|/|b| = 2.871322e+08
GCR:    10 iterations, <r,r> = 5.210814e+22, |r|/|b| = 2.802095e+08
GCR:    11 iterations, <r,r> = 5.208918e+22, |r|/|b| = 2.801585e+08
GCR:    12 iterations, <r,r> = 5.208462e+22, |r|/|b| = 2.801463e+08
GCR:    13 iterations, <r,r> = 5.208252e+22, |r|/|b| = 2.801406e+08
GCR:    14 iterations, <r,r> = 5.205387e+22, |r|/|b| = 2.800635e+08
GCR:    15 iterations, <r,r> = 5.205242e+22, |r|/|b| = 2.800596e+08
GCR:    16 iterations, <r,r> = 5.205143e+22, |r|/|b| = 2.800570e+08
```

`./run.sh` includes the command noted above; the compile was identical. I can confirm that `--partition 0` is (still) fine, and `kd-optimized` w/out dropping the long links is fine with or without partitioning.

**Comment by bjoo** [comment]
Chroma seems to run split grid happily without hanging! Thanks @maddyscientist !!!

**Comment by maddyscientist** [comment]
cscs-ci run

**Comment by weinbe2** [comment]
@maddyscientist your latest commits gave me a successful 2-level solve, thanks!! I'm going to test a more typical solver workflow just to make sure there are no other surprises, and assuming there aren't any this PR will be good-to-go from my perspective.

**Review by weinbe2 — APPROVED** [review]
Everything now looks good with HISQ MG---I tried various partitionings, batch sizes, etc, and everything worked out without issue. Thanks @maddyscientist !

**Pull request merged**
