### PR TITLE
add 'one-size-fits-all' doxygen input file

### PR DESCRIPTION
**Pull request by kostrzewa**
This may be useful to others, please comment if you (dis-)like the fact that it creates another directory...

### CODE REVIEW

**Comment by mathiaswagner** [comment]
Eventually would be great to get that into cmake somehow ...

**Comment by mathiaswagner** [comment]
https://vicrucann.github.io/tutorials/quick-cmake-doxygen/ has some good hints for cmake integration.

There is also https://cmake.org/cmake/help/v3.0/module/FindDoxygen.html.

**Comment by kostrzewa** [comment]
okay, will do, so you'd like the docs to be created in ```build``` ?

**Comment by mathiaswagner** [comment]
Guess we can leave that up for discussion. It was my first reaction to always keep the build dir clean but I haven't given it any more thought yet.

**Comment by rbabich** [comment]
For comparison, the doxygen input file that we've traditionally used is here: https://github.com/lattice/quda-ref/tree/master

**Comment by mathiaswagner** [comment]
It's been a long time but I still like the doxygen idea. @kostrzewa, @maddyscientist  Where do we stand on this? Do we want better cmake integration here?

**Comment by maddyscientist** [comment]
Yes, we want good cmake integration with doxygen is very relevant would be good.  Possible for the 0.9.0 release you think?

**Comment by mathiaswagner** [comment]
Pulling this into a branch of the github repository. I will add a follow up pull request for merge into develop.

**Pull request merged**
