### PR TITLE
Add more ROCm versions to CI

### PR DESCRIPTION
**Pull request by dmcdougall**
Let's see if this works... :)

### CODE REVIEW

**Comment by maddyscientist** [comment]
@dmcdougall I see the inline assembly warnings are now gone with 5.6.  Is there any reason to keep around 5.5 or can we dump this and make the builds `STRICT` now?

**Comment by dmcdougall** [comment]
> Is there any reason to keep around 5.5 or can we dump this and make the builds STRICT now?

You took the wind out of my sails :)

That is indeed my next step, I just wanted to sanity check the multiple version infrastructure did what I expected it to do.

Don't merge this yet; I'll update this PR with more commits.

**Comment by dmcdougall** [comment]
@maddyscientist Can you kick off another build please?

**Comment by dmcdougall** [comment]
Hmmm, these `STRICT` builds succeeded but there are still warnings.  I'll dig.

**Comment by dmcdougall** [comment]
Oh [this](https://github.com/lattice/quda/blob/develop/lib/targets/hip/target_hip.cmake#L106) turns off the error (`STRICT` users `-Werror`).  It doesn't turn off the warning.

**Review by maddyscientist — APPROVED** [review]

**Comment by maddyscientist** [comment]
@dmcdougall good to merge now from your point of view?

**Comment by dmcdougall** [comment]
Yep.  Thanks.

**Pull request merged**
