### PR TITLE
Fixes issue #405

### PR DESCRIPTION
**Pull request by AlexVaq**
Fixes contraction wrong result while tuning for the plus-minus option.

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/lattice/quda/pull/419" target="_blank">ReviewNinja

**Comment by AlexVaq** [comment]
This is a fairly uncontroversial commit that solves issue #405, so I suggest we merge immediately and close #405.

**Comment by maddyscientist** [comment]
This should go into release/0.8.x not develop.

**Comment by AlexVaq** [comment]
Ops, I think I took the wrong branch. Should I create a new pull request based on release/0.8.x?

**Comment by maddyscientist** [comment]
Yes please. It would be nice to fix this bug in the 0.8.0 release.

**Comment by AlexVaq** [comment]
Closing then.

**Pull request closed without merging**
