### PR TITLE
potential fix for cmake cublas issues

### PR DESCRIPTION
**Pull request by mathiaswagner**
potential fix for issue #883.

@kostrzewa Do you mind testing this to verify it resolves the issue on your system?

### CODE REVIEW

**Comment by kostrzewa** [comment]
Compiling right now, if this works it's a nice and simple workaround :)

**Comment by mathiaswagner** [comment]
@kostrzewa any luck with that?

**Comment by kostrzewa** [comment]
This seems to fix #883 for me

**Comment by mathiaswagner** [comment]
Thanks for checking.

**Comment by maddyscientist** [comment]
Shouldn’t this be going into release not develop?

**Comment by mathiaswagner** [comment]
Yes, good point. I’ll reopen that for release later.

**Comment by mathiaswagner** [comment]
Backported to release in #918. Will just merge release into develop again to get fixes here hence closing this.

**Pull request closed without merging**
