### PR TITLE
added date to NEWS,README file and fixed some typos

### PR DESCRIPTION
**Pull request by mathiaswagner**

### CODE REVIEW

**Comment by maddyscientist** [comment]
I've pushed all the fixes needed for the TIFR Fortran application: as well as Fortran interface fixes, I had to expose an option as whether to overwrite the momentum field or not.  No changes should be needed in MILC, as these changes would only affect QUDA <-> QUDA MILC interface interactions, and no other application.

From my point of view, I believe QUDA 0.8 is now done :smile:

**Comment by mathiaswagner** [comment]
(y)

I will have a look into that and the copy issue. I’ll also have a look at the cmake copy issue. I believe this might be a glitch with some files or links in the file system.
If I cannot reproduce this today I’d ask you to check the issue using a fresh build directory. If it is gone then I guess we can leave it until anybody else hits that.

**Comment by maddyscientist** [comment]
I reproduced the copy issue on a fresh build directory last night. It only seems to happen with rebuilds though, not the first build.  Perhaps some kind of permissions issue?

**Comment by mathiaswagner** [comment]
Can you point me to your build directory? I failed to reproduce it during rebuilds so far.

On 01.02.2016, at 15:57, maddyscientist <notifications@github.com<mailto:notifications@github.com>> wrote:


I reproduced the copy issue on a fresh build directory last night. It only seems to happen with rebuilds though, not the first build. Perhaps some kind of permissions issue?

-
Reply to this email directly or view it on GitHub<https://github.com/lattice/quda/pull/434#issuecomment-178003107>.

NVIDIA GmbH, Wuerselen, Germany, Amtsgericht Aachen, HRB 8361
Managing Director: Karen Theresa Burns

-----------------------------------------------------------------------------------
This email message is for the sole use of the intended recipient(s) and may contain
confidential information.  Any unauthorized review, use, disclosure or distribution
is prohibited.  If you are not the intended recipient, please contact the sender by
reply email and destroy all copies of the original message.
-----------------------------------------------------------------------------------

**Comment by maddyscientist** [comment]
/tmp/quda-0.8

**Comment by mathiaswagner** [comment]
Still does not show up for me. Things that might help:

* add 'VERBATIM' to the copy command
* delete the include directory and copy it again

```
#ADD_CUSTOM_COMMAND(TARGET quda PRE_LINK ${CMAKE_COMMAND} -E remove_directory ${CMAKE_BINARY_DIR}/include VERBATIM)
ADD_CUSTOM_COMMAND(TARGET quda POST_BUILD COMMAND ${CMAKE_COMMAND} -E copy_directory ${CMAKE_SOURCE_DIR}/include ${CMAKE_BINARY_DIR}/include VERBATIM)
```

in `lib/CMakeLitst.txt`

to try the second option obviously you need to uncomment the first line above. The current command to copy the include dir should be around line 60.

I need to ask you to give that a try. Still puzzled what is going on there.

**Pull request merged**
