### PR TITLE
MILC interface for two-link quark smearing

### PR DESCRIPTION
**Pull request by hwancheolJeong**
This PR adds a MILC interface for the two-link quark smearing.

### CODE REVIEW

**Comment by mathiaswagner** [comment]
Jenkins: Can one of the admins verify this patch?

**Comment by mathiaswagner** [comment]
Jenkins: Can one of the admins verify this patch?

**Comment by maddyscientist** [comment]
@Jenkins ok to test

**Comment by maddyscientist** [comment]
@hwancheolJeong can you point us at the MILC branch which can be used to test against this?

**Comment by hwancheolJeong** [comment]
> @hwancheolJeong can you point us at the MILC branch which can be used to test against this?

@maddyscientist You can test it with the MILC's develop branch. You should enable `WANT_GSMEAR_GPU` flag in Makefile (https://github.com/milc-qcd/milc_qcd/blob/develop/Makefile#L432).
This smearing is called `covariant_gaussian` in the MILC code. In case you need an application for test, refer to my test application https://github.com/hwancheolJeong/milc_qcd/tree/feature/gaussianSmearing/ks_gauss_smear. It provides an application `ks_gauss_smear` and its test for `make check`.

**Review by maddyscientist — APPROVED** [review]
Thanks @hwancheolJeong for filling in this missing piece

**Pull request merged**
