### PR TITLE
Time staples removed from smearing

### PR DESCRIPTION
**Pull request by AlexVaq**
I believe this is what most users would want to use

### CODE REVIEW

**Comment by AlexVaq** [comment]
Don't merge this yet, I'm still checking it's right

**Comment by AlexVaq** [comment]
This is ready for merge.

Before, let me explain the modification. I believe my old implementation was 4D smearing, and someone (or maybe me, I don't remember, this code it's old) limited the for loop of smearing to do only 3D smearing. The problem was that the computed staples for smearing were 4D anyway, which turned out to give incorrect results.

**Comment by AlexVaq** [comment]
Now, after merging this pull request, I'll create the new feature requested by Dean, i.e., you can choose between 3D or 4D smearing, and you can leave out the direction you want. But first let's make the code consistent and usable.

**Comment by AlexVaq** [comment]
I think this last addition was really important. We feel this code is ready for production, I'm going to stop messing with it until merge.

**Comment by maddyscientist** [comment]
Looks like this fails compilation, though I am confused why it appears to have built successfully for CUDA 6.5 and 7.5 and only fails for 7.0.  The lack of `nDim` declaration looks terminal. 
```
gauge_ape.cu(141): error: identifier "nDim" is undefined
          detected during:
            instantiation of "void quda::GaugeAPE<Float, GaugeOr, GaugeDs>::apply(const cudaStream_t &) [with Float=float, GaugeOr=quda::FloatNOrder<float, 18, 2, 18>, GaugeDs=quda::FloatNOrder<float, 18, 2, 18>]" 
(167): here
            instantiation of "quda::GaugeAPE<Float, GaugeOr, GaugeDs>::GaugeAPE(quda::GaugeAPEArg<Float, GaugeOr, GaugeDs> &, QudaFieldLocation) [with Float=float, GaugeOr=quda::FloatNOrder<float, 18, 2, 18>, GaugeDs=quda::FloatNOrder<float, 18, 2, 18>]" 
(213): here
            instantiation of "void quda::APEStep(GaugeOr, GaugeDs, const quda::GaugeField &, Float, QudaFieldLocation) [with Float=float, GaugeOr=quda::FloatNOrder<float, 18, 2, 18>, GaugeDs=quda::FloatNOrder<float, 18, 2, 18>]" 
(231): here
            instantiation of "void quda::APEStep(quda::GaugeField &, const quda::GaugeField &, Float, QudaFieldLocation) [with Float=float]" 
(295): here
```

**Comment by AlexVaq** [comment]
Ops, that nDim shouldn't be there. I'll fix it as soon as I can.

**Comment by AlexVaq** [comment]
Is there anything preventing this from merging?

**Comment by maddyscientist** [comment]
Did you fix the nDim problem? That was what was blocking this.

**Comment by AlexVaq** [comment]
nDim was removed in the last commit

**Comment by maddyscientist** [comment]
Ok, I didn't see that.  I was going by your last comment that you were going to fix it. Will merge this soon then.

**Comment by AlexVaq** [comment]
Nice! There are some important fixes for APE smearing there too.

I'll start working on Dean's suggestion as soon as I have a break.

**Pull request merged**
