### PR TITLE
Feature/twist clover cleanup

### LINKED ISSUE #124: Remove GPUDirect=no functionality
Given that sharing pinned buffers between IB and CUDA has been part of CUDA for over two years now, and we've had no complaints of it not working for over a year, I propose that we remove all #ifdef GPUDIRECT macros from QUDA and delete all non-GPUDirect functionality from the library.

This will clean up the communications interfaces as well and will mean that when gpu-aware MPI functionality is supported in QUDA, the GPUDirect name overload will not occur.  I would suggest at that point in fact that we simply use GPUDirect to designate that GPU-aware mpi is being used.

Any objections to this clean up?

### PR DESCRIPTION
**Pull request by maddyscientist**
This pull request consists of a complete rewrite of dslash_quda.cu, and also includes multiple framework improvements to facilitate this rewrite.
* Fixes compilation for CUDA 9.0 by updating the use of warp synchronous intrinsics to use the new `_sync` variations introduced with CUDA 9.0 and updated to the latest version of CUB
* Volta optimization for dslash kernels: prefer large shared-memory carve out  
* Add texture support to `colorspinor::FloatNOrder` and `clover::FloatNOrder`accessors for fast half-precision data reading
* Add texture support to `gauge::FloatOrder` accessor, though for now not enabled (will be revisited)
* Add new `HMatrix` class which wraps around triangular packed Hermitian matrices (e.g., clover) and provides support for basic arithmetic operations that are optimal
* Added new `linalg` namespace, which includes `linalg::cholesky`, `linalg::forward`, and `linalg::backward` which are highly optimized for solving dense Hermitian matrix systems (e.g., solving for the Clover matrix)
* Complete rewrite of all kernels in dslash_quda.cu to use high-level framework.  This dramatically simplifies the kernels.  No performance regressions, and in many cases, new code is significantly faster (e.g., dynamic clover inversion using `linalg::cholesky`)
* Removal of now redundant core files in dslash_core
* Cleanup of backup and restore methods to simplify writing `Tunable::preTune` and `Tunable::postTune`
* Removes legacy `GPU_DIRECT` build option (closes #124)
* Other small cleanup and fixes

Asking for @alexstrel and @AlexVaq to review these changes since this affects kernels written by you folks.

### CODE REVIEW

**Comment by maddyscientist** [comment]
@alexstrel As discussed offline, there is the still the outstanding question of the sign difference in the non-degenerate twisted-mass convention between `DiracTwistedMassPC::Dslash` and `DiracTwistedMassPC::DslashXpay`.

**Comment by AlexVaq** [comment]
That was huge. It will take me some time to go through this.

**Comment by kostrzewa** [comment]
> @alexstrel As discussed offline, there is the still the outstanding question of the sign difference in the non-degenerate twisted-mass convention between DiracTwistedMassPC::Dslash and DiracTwistedMassPC::DslashXpay.
 
@maddyscientist I haven't had the time recently to do much on QUDA and I'm sorry about that, but his caught my eye while looking through my mails. Without looking at the code now, I would say that the non-EO-PC Dslash should do:

``` ( 4+m + clover + i \mu \gamma_5 ) - 1/2 hopping``` for the TWIST_PLUS flavour

In the EO-preconditioned case, however, the PC operator should have:

```Dslash = ( 4+m + clover - i\mu\gamma_5 ) / ( ( 4+m + clover)^2 + \mu^2 ) * hopping```

```AChiMinusBDPsi = ( 4+m + clover + i \mu \gamma_5 ) - 1/4 hopping * Dslash```

For the non-degenerate case, one gets extra flavour-off-diagonal contributions proportional to the mass splitting which have a plus sign in Dslash and a minus sign in AChiMinusBDPsi.

So we have:

``` Dslash = (4+m+clover-i\mu\gamma_5\tau3+\epsilon\tau1)/((4+m+clover)^2 + \mu^2 - \epsilon^2) * hopping```
```AChiMinusBDPsi= (4+m+clover + i\mu\gamma_5\tau3 - \epsilon\tau1) - 1/4 hopping* Dslash```

Hope the sloppy notation doesn't make things unclear.

**Comment by maddyscientist** [comment]
I've applied the new framework cleanup to the field strength tensor (0534a0c925960ef2aea703fd6de8fef825570b68), clover field creation (689f1b3582ae94592e280b8d6149065926ab02da) and clover inversion kernels (https://github.com/lattice/quda/pull/642/commits/4c1107e887cf0ea569746ddac2db423c9ab3025d).  New result is these routines are now simpler, and 1.2x, 3x, 4.5x faster respectively.

**Comment by maddyscientist** [comment]
Before I forget, recording off-line feedback from @AlexVaq:
* Link problem when built as shared library
* CUDA 9.0 compilation errors
* Failes to compile with `QUDA_CONTRACT` enabled

**Comment by maddyscientist** [comment]
QUDA should now be safe for CUDA 9.x (I've updated to the latest CUB, and applied the required fixes to the generics and trove packages for CUDA 9's new warp synchronous intrinsics).  The contraction code is also fixed.  I've checked with CUDA 8.0 / GCC 5.4 and CUDA 9.0 / GCC 6.3.

@AlexVaq and @alexstrel, I haven't seen any problem related to building as a shared library.  Can you check if this is still a problem?

**Comment by AlexVaq** [comment]
Ok, I'll try and let you know, but my eta is monday...

**Comment by maddyscientist** [comment]
Sure, Monday is fine.  Thanks.

**Comment by maddyscientist** [comment]
Just pushed some more minor cleanup and performance fixes.  Notable is the performance Fmunu calculation now reaches 36% of peak FMA performance on P100 (1.9 TFLOPS FP64) which I think makes it the highest performing kernel in QUDA. 😄

**Comment by maddyscientist** [comment]
@mathiaswagner I need your help here: Jenkins is reporting many compilation warnings (which are treated as errors of course).  Trouble is I cannot reproduce these when using exactly the same compiler and cmake invocation that gives these warnings.

**Comment by mathiaswagner** [comment]
Steps to reproduce the error in Jenkins builds:
```
git checkout feature/twist-clover-cleanup
cd cloverbuild
CC=/usr/bin/gcc-5 CXX=/usr/bin/g++-5 /scratch/jenkins/cmake-3.5.2-Linux-x86_64/bin/cmake -G Ninja -D CMAKE_BUILD_TYPE=STRICT -DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda-8.0 -DQUDA_GPU_ARCH=sm_60 -DQUDA_MPI=yes -DQUDA_BUILD_SHAREDLIB=yes -DMPI_CXX_COMPILER=/usr/local/mvapich2-2.2-gcc-5.4/bin/mpic++ -DMPI_C_COMPILER=/usr/local/mvapich2-2.2-gcc-5.4/bin/mpicc -DQUDA_BUILD_SHAREDLIB=yes ~/qudagit
```

Now I'll try to understand what is going wrong and why ...

**Comment by maddyscientist** [comment]
@mathiaswagner My last push should have fixed all compiler warnings now.  This should be good for merging now.  This branch should also allow CUDA 9.0 to compile with no warnings, so we could add that to the Jenkins testing now.

**Comment by maddyscientist** [comment]
@alexstrel did you ever look into the sign ambiguity of the non-degenerate twisted-mass fermions between `dslash` and `dslashXpay`?  Though, having said that, I'm not overly worried about at the moment, since code gives the right answer, and the dslash kernels will shortly be ripped up and rewritten in the high-level framework.

**Comment by alexstrel** [comment]
@maddyscientist sorry, did not finish yet. I can create a hotfix after the merge.

**Pull request merged**
