### PR TITLE
Hotfix/delta mu

### PR DESCRIPTION
**Pull request by cpviolator**
Addresses #426 in the manner used by ETMC.

### CODE REVIEW

**Comment by mathiaswagner** [comment]
Jenkins: Can one of the admins verify this patch?

**Comment by mathiaswagner** [comment]
Jenkins: Can one of the admins verify this patch?

**Comment by mathiaswagner** [comment]
Jenkins: Can one of the admins verify this patch?

**Comment by mathiaswagner** [comment]
Jenkins: Can one of the admins verify this patch?

**Comment by maddyscientist** [comment]
@cpviolator I'm wondering if multiplicative changes are best versus absolute value setting.  Thoughts?

Also wondering, if while making this functionality available, whether we can fix #426 at the same time?

**Comment by cpviolator** [comment]
@maddyscientist I've been doing all my tuning etc in terms of multiplicative factors, and relationships between spacetime lattice extent and MG block size, I can easliy switch the QUDA code to absolute values if you'd prefer.

As for #426, I was studying the paper Accelerating Lattice QCD Multigrid on GPUs Using Fine-Grained Parallelization to see what would be involved. I was immediately stumped by the transition of eq(2) to eq(3), where the diagonal term containing the mass, constant, and clover matrix all seem to go to a Kronecker delta with unit coefficient. Presumably, as mentioned above, one must add a constant to the diagonal of the coarse-grid Dirac operator. Is it as simple as looping over all x = x' and adding a \delta m?

**Comment by mathiaswagner** [comment]
Jenkins: Can one of the admins verify this patch?

**Comment by mathiaswagner** [comment]
add to whitelist

**Comment by cpviolator** [comment]
@mathiaswagner Thank you, good to go.

**Comment by cpviolator** [comment]
That's a weird bug re sm_2.0. Do you know what the cause is?

**Comment by mathiaswagner** [comment]
looks like this is a system issue. I triggered a rebuild.

**Comment by cpviolator** [comment]
@maddyscientist Just a comment about using multiplicative changes rather than absolute values for delta_*MG variables. Because changes to these variables are hardcoded into multigrid_solver, I wanted to ensure that if no arguments are passed, no changes to the original mu, kappa, mass, variables would be implemented. The easiest way to do this is to make the changes multiplicative, and have the defaults set to 1.0.

**Comment by mathiaswagner** [comment]
Somehow the diff looks odd. Did you merge the latest develop in that? It shows a lot of commits that are already merged into develop and thus should not show up in the diff anymore.

**Comment by cpviolator** [comment]
I don't think so. I may have used a non updated git pull to push the changes. Can we revert everything you think is fishy and start over? The changes are minor.

**Comment by cpviolator** [comment]
BTW, these changes on the delta_mu branch are added to facilitate a plug-in we are writing:

https://github.com/ETMC-QUDA/quda-QKXTM-Multigrid-PlugIn

It is designed to compile against a mainline QUDA build, but expects minor changes to QUDA files. Having them in mainline quda both facilitates the Twisted MG upgrades to mainline QUDA, and allows us to compile a plug-in against QUDA's latest commits without manually upgrading our code.

**Comment by mathiaswagner** [comment]
Ok. Just merged the most recent develop into the hot fix branch and now the diff looks good.

**Comment by cpviolator** [comment]
Thank you @mathiaswagner. I'm testing one more change to color_spinor_field.h that we need. If the test passes, and we can put that change (3 lines) to mainline QUDA, we will have a very compact plug-in that can be used by anyone with a mainline QUDA installation.

**Comment by mathiaswagner** [comment]
Sure. Just tell us when this pull is good to go.

**Comment by cpviolator** [comment]
@maddyscientist @mathiaswagner Shall we this branch as @sbacchio's #581 seems to be the way to go?

**Comment by cpviolator** [comment]
And `hotfix_delta_mu` too?

**Pull request closed without merging**
