### PR TITLE
Create Codeowners

### PR DESCRIPTION
**Pull request by mathiaswagner**
Initial version of code owners to assign reviewers for target specific parts in QUDA
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners

### CODE REVIEW

**Comment by mathiaswagner** [comment]
just did some experiments here to get the CODEOWNSERS file to verify

**Comment by jcosborn** [comment]
How can we see who is in each group (I can't see the settings for the repo)?

**Review by jcosborn — APPROVED** [review]

**Review by maddyscientist — APPROVED** [review]

**Comment by mathiaswagner** [comment]
@bjoo do you mind approving when this is ok for you?

**Review by bjoo — APPROVED** [review]
I am happy with this

**Pull request merged**
