### PR TITLE
Feature/twisted hasen

### PR DESCRIPTION
**Pull request by bjoo**
Added DiracCloverHasenbuschTwist and DiracCloverHasenbuschTwistPC operators. Added extra kernels, and tests. Checked from Chroma that GCR solver works. MG coarsening still missing tho.
The preconditioned operators are:
Asymmetric: 
 A_oo -kappa^2 D)oe (A_ee)^{-1} D_eo -/+  i \mu \gamma_5

Symmetric
1 -/+ i \mu \gamma_5 A_oo  - kappa^2 (A_oo)^{-1} D_oe A_ee^{-1} D_eo

(and e <-> o)
The unprec operators are: 
corresponding to symmetric:

[ A_ee                       -kappa  D_eo                     ]
[-kappa D_oe  A_oo(1-i \mu \gamma_5 A_oo ) ]

and corresponding to Asymmetric

[ A_ee                       - kappa D_eo           ]
[ -kappa D_eo   A_oo - i \mu \gamma_5 ]

tho these unprec ops are primarily for multigrid and should not be used for anything physical.

In terms of flopcounts:   

- i \mu \gamma_5 terms cost an extra 48 FLOPS per site (1 vector FMA on real & complex parts)
- i \mu \gamma_5 A_oo terms cost an extra 48 + 504 FLOPS per site ( 1 vector FMA on real & complex parts, plus clover application)

In terms of bytes: 
Apart from the symmetric preconditioned operator the requisite input spinor and A term is already always loaded so no need for extra memory traffic in principle. In terms of the symmetric preconditioned operator one needs to load in the A_oo term as extra (since only the A^{-1} terms are used) unless dynamic clover is enabled when the A^{-1} term loaded is the A term.

### CODE REVIEW

**Comment by mathiaswagner** [comment]
@bjoo Should that go into the def-rewrite branch first? It seems like it is based on that so until we have fully tested that we cannot merge your changes into develop. We could do a merge into dwf-rewrite earlier.

**Comment by bjoo** [comment]
Yes. My mistake. I can try to change when I get back to our place. Sorry,  B

Sent from Blue<http://www.bluemail.me/r?b=14562>
On Mar 1, 2019, at 11:20 AM, Mathias Wagner <notifications@github.com<mailto:notifications@github.com>> wrote:

@bjoo<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbjoo&data=02%7C01%7Cbjoo%40jlab.org%7Ccdc118c793454a897c8408d69e61c942%7Cb4d7ee1f4fb34f0690372b5b522042ab%7C1%7C0%7C636870540151176506&sdata=mvkxnoWMr5Oy9iIGWA4XdrzfIEu8idJ0tFp9ODx9qzs%3D&reserved=0> Should that go into the def-rewrite branch first? It seems like it is based on that so until we have fully tested that we cannot merge your changes into develop. We could do a merge into dwf-rewrite earlier.

**Comment by maddyscientist** [comment]
@bjoo no need to update the destination of the pull, since we should get #776 merged next week, and I'd like to keep your changes and additions out of that.

Note that since you've requested to merge from outside the lattice org, you'll have to make any fixes we need done before we can merge.  For a significant pull like this, I think we'd prefer to have merge requests come from within the org in general.

Beyond the blocker of #776, you also need to remerge in from feature/dwf-rewrite, to get all the build test fixes for feature/dwf that I've added in the past week.  This will allow us to see if any of your code additions pass all the build tests.

**Comment by bjoo** [comment]
Hmm... I see that some of the tests have failed. Is there a way to check the failures? 
I clicked on details but it tried to take me to a site that said 'site can't be reached'.

**Comment by bjoo** [comment]
After discussion with @maddyscientist it was decided that it may be best to push the feature branch into the quda repo. So I have done that. However, I can't change the branch to be merged in this PR. So I am closing it. It is being superceded (continued) by PR #850

**Pull request closed without merging**
