### PR TITLE
add a few explicit instantiations

### PR DESCRIPTION
**Pull request by jcosborn**

### CODE REVIEW

**Comment by mathiaswagner** [comment]
Jenkins: Can one of the admins verify this patch?

**Comment by maddyscientist** [comment]
ok to test

**Comment by weinbe2** [comment]
@mathiaswagner I'm confused about why Jenkins isn't getting launched for this---the only weird nuance I can think of it this is getting merged into `lattice:develop` as opposed to just `develop` since it's merging from @jcosborn 's fork, and that's tripping up some comparison?

**Review by maddyscientist — APPROVED** [review]
Trivial, thanks for the addition

**Pull request merged**
