### PR TITLE
Fix the timer conflicts and a potential double delete in PCG

### PR DESCRIPTION
**Pull request by hummingtree**
1. The preconditioned CG uses the same `TimeProfile` for both the outer solver and the inner preconditioned solver, which leads to timer conflicts. This PR creates a separate `TimeProfile` and pass it to the preconditioned solver.
2. Change the `delete` condition for `x_sloppy` and `r_sloppy` the same as their corresponding `new` condition to avoid potential segmentation faults.

### CODE REVIEW

**Comment by maddyscientist** [comment]
One question: GCR (inv_gcr_quda.cpp) uses the same `TimeProfile` instance for the preconditioner and the outer solver.  Is there something in CG that makes this not possible?

**Comment by hummingtree** [comment]
> One question: GCR (inv_gcr_quda.cpp) uses the same `TimeProfile` instance for the preconditioner and the outer solver. Is there something in CG that makes this not possible?

I just tried GCR with CG as the preconditioning solver and saw the same timer conflict.

**Comment by maddyscientist** [comment]
😄  Can you tell me what command you used for this so I can reproduce?

**Comment by hummingtree** [comment]
Hmm ... I was trying in my branch and say the timer conflict. And I can't reproduce the problem in develop for either PCG or GCR ...

**Comment by maddyscientist** [comment]
It's possible this is a bug then that has since been fixed since you branched.

**Comment by maddyscientist** [comment]
Does the bug disappear if you merge in develop into your branch?

**Comment by hummingtree** [comment]
I believe so since CG (not PCG) has changed a lot since last time I merged. Let me do the merge (which will take a while.)

**Comment by hummingtree** [comment]
I have merged the lastest `develop` into my `feature/overlapping-schwarz` and still gets timer conflicts. I haven't been able to find any clue in `inv_pcg_quda.cpp` and `inv_cg_quda.cpp`.

**Review by maddyscientist — APPROVED** [review]

**Comment by maddyscientist** [comment]
This pull is all good and fixes a bug that lead to segmentation faults.  We can merge this in once the latest builds have completed. 

Thanks @hummingtree!

**Pull request merged**
