### PR TITLE
Hotfix/cmake power

### PR DESCRIPTION
**Pull request by mathiaswagner**
For `RELEASE` build type use

`-mcpu / -mtune -Ofast` flags on POWER systems as `-march` is not supported.

This is just a quick workaround and we should look into a better solution, see #762.

### CODE REVIEW

**Comment by maddyscientist** [comment]
@walkloud you're assigned to review this pull request.  Are you ok with it?

**Comment by walkloud** [comment]
@mathiaswagner in the fix, you have the following
```-mcpu=native -mtune=native```
while in my build, I have
```-mcpu=power9 -mtune=power9```
have you tried the `native`?  I've been meaning to (but haven't yet) checked if that works

**Comment by mathiaswagner** [comment]
I just tried and it seems to compile fine (at least the compiler does not complain about the flags) and in that process realized that I also needed to fix my check.
Should be fine now but our CI is purely x86 right now so any additional checks on other machines are highly appreciated.

But we can always improve the fix later if is not yet perfect.

**Comment by walkloud** [comment]
@mathiaswagner @maddyscientist the code is compiling with those changes, `-mcpu=native -mtune=native`, would you like me to run a performance test as well with one of the tests?

**Comment by mathiaswagner** [comment]
Thanks for checking @walkloud. I don't think the code will not run if you can compile it but of course a quick firing up of one of the quad internal tests (or whatever is least effort for you) is appreciated. Just to be sure ...

**Comment by walkloud** [comment]
OK - I’ll do an MDWF test tomorrow

I wasn’t thinking of working or not, but if the `native` gets the same optimization as `power9`

**Pull request merged**
