### PR TITLE
Feature/fgmresdr2

### PR DESCRIPTION
**Pull request by MichaelBaldauf**
Implemented the F-GMRES-DR solver presented in **http://arxiv.org/abs/1204.5463** with slight modifications in order to make it more robust against floating point errors accumulating in a mixed precision environment.
The solver assumes that Quda was linked against Magma (everything was tested with Magma 1.6.2).

Analogously to all other QUDA solvers, F-GMRES-DRs vital parameters are defined
within QudaInvertParam. Among all possible settings only two parameters are distinct
from all other available solvers, namely the total size of the used Krylov space, and the
number of Ritz vectors used for deflation. These two parameters were assigned to
**QudaInvertParam.gcrNkrylov  // size of Krylov space
QudaInvertParam.deflation_grid // # of Ritz vectors for deflation**
since their names are the most adequate for the intended purpose.
The following code snippet set up GMRES in a default way:
**QudaInvertParam inv_param = newQudaInvertParam();
inv_param.inv_type = QUDA_GMRES_INVERTER;
inv_param.gcrNkrylov = 8; // 8 Krylov vectors
inv_param.deflation_grid = 1; // 1 Ritz vector for deflation**
For a short example of the overall interface see the appended file “invert_test.cpp”,
which belongs into the “tests” directory.

### CODE REVIEW

**Comment by maddyscientist** [comment]
Thanks @MichaelBaldauf.  As @mathiaswagner noted we've got GTC coming up so we might not get a chance to properly look at this until after then.  At first glance this looks good though.

**Comment by mathiaswagner** [comment]
Jenkins: Can one of the admins verify this patch?

**Comment by mathiaswagner** [comment]
Jenkins: Can one of the admins verify this patch?

**Comment by mathiaswagner** [comment]
ok to test

**Comment by mathiaswagner** [comment]
Jenkins: Can one of the admins verify this patch?

**Comment by mathiaswagner** [comment]
@Jenkins ok to test

**Comment by mathiaswagner** [comment]
Jenkins: Can one of the admins verify this patch?

**Comment by mathiaswagner** [comment]
Jenkins: Can one of the admins verify this patch?

**Comment by mathiaswagner** [comment]
Jenkins: Can one of the admins verify this patch?

**Comment by mathiaswagner** [comment]
Relevant parts of this have been integrated into QUDA through #612.

**Pull request closed without merging**
