### PR TITLE
Hotfix/ccomplex

### PR DESCRIPTION
**Pull request by maddyscientist**
Fixes a bug observed with some compilers (nvc++, rocm clang) where the compiler fails to compile if:
* The source code includes the `complex.h` / `complex` header
* A template class name is given as `I`

I've also fixed a warning with nvc++ and reduced the argument size for the dilution kernel.

### CODE REVIEW

**Review by hummingtree — APPROVED** [review]
The code change looks all good to me but just curious why would the `typename I` matter here?

**Comment by stevengottlieb** [comment]
I am compiling this branch on Vista at TACC.  Things seemed to be going well, getting past the point where there was an error before.  However, there was a long pause here:

[ 78%] Building CUDA object lib/CMakeFiles/quda.dir/dslash_domain_wall_4d_m5pre.cu.o
[ 78%] Building CUDA object lib/CMakeFiles/quda.dir/dslash_domain_wall_4d_m5pre_m5inv.cu.o
[ 79%] Building CUDA object lib/CMakeFiles/quda.dir/dslash_domain_wall_4d_m5inv_m5pre.cu.o
[ 79%] Building CUDA object lib/CMakeFiles/quda.dir/dslash_domain_wall_4d_m5inv_m5inv.cu.o
[ 79%] Building CUDA object lib/CMakeFiles/quda.dir/dslash_domain_wall_4d_m5mob.cu.o
[ 79%] Building CUDA object lib/CMakeFiles/quda.dir/dslash_domain_wall_4d_m5pre_m5mob.cu.o
[ 80%] Building CUDA object lib/CMakeFiles/quda.dir/dslash_pack2.cu.o
[ 80%] Building CUDA object lib/CMakeFiles/quda.dir/laplace.cu.o
[ 80%] Building CUDA object lib/CMakeFiles/quda.dir/covariant_derivative.cu.o
[ 80%] Building CUDA object lib/CMakeFiles/quda.dir/staggered_quark_smearing.cu.o

Then compilation failed on a host reference function:

[ 84%] Building CXX object tests/CMakeFiles/quda_test.dir/host_reference/gauge_force_reference.cpp.o
[ 84%] Building CXX object tests/CMakeFiles/quda_test.dir/utils/misc.cpp.o
"/home1/00282/tg455536/from_frontera/compile_vista/build/_deps/eigen-src/Eigen/src/Core/arch/NEON/Complex.h", line 397: error: statement expressions are only allowed in block scope
    static uint64x2_t p2ul_CONJ_XOR = vld1q_u64( p2ul_conj_XOR_DATA );
                                      ^

1 error detected in the compilation of "/home1/00282/tg455536/from_frontera/compile_vista/quda/tests/host_reference/clover_force_reference.cpp".
make[2]: *** [tests/CMakeFiles/quda_test.dir/build.make:296: tests/CMakeFiles/quda_test.dir/host_reference/clover_force_reference.cpp.o] Error 2

Is this something specific to ARM?  I am not sure what NEON refers to.

Thanks,
Steve

On Aug 13, 2024, at 4:39 PM, maddyscientist ***@***.***> wrote:


Fixes a bug observed with some compilers (nvc++, rocm clang) where the compiler fails to compile if:

  *   The source code includes the complex.h / complex header
  *   A template class name is given as I

I've also fixed a warning with nvc++ and reduced the argument size for the dilution kernel.

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/lattice/quda/pull/1485

Commit Summary

  *   c76ae44<https://github.com/lattice/quda/pull/1485/commits/c76ae4426fdefe93b1c422d078b897d3edeaf555> Remove complex.h inclusion
  *   7ef6d87<https://github.com/lattice/quda/pull/1485/commits/7ef6d879a2544098516ff5d5886b3da0d7333c8c> Fix nvc++ warning
  *   1ec0607<https://github.com/lattice/quda/pull/1485/commits/1ec060734dc192d1308cd370bfc514d96350714a> Reduce arg size for spinor dilution

File Changes

(4 files<https://github.com/lattice/quda/pull/1485/files>)

  *   M include/kernels/spinor_dilute.cuh<https://github.com/lattice/quda/pull/1485/files#diff-c8996253331dd5b951565183eb4c563b377e0a494ea3bf460f1d9941ed2a872f> (2)
  *   M lib/interface_quda.cpp<https://github.com/lattice/quda/pull/1485/files#diff-0cea12be36de2a7423cca02391b81d66534bda503b565735dc5b4000f4fcda10> (1)
  *   M lib/targets/cuda/blas_lapack_cublas.cpp<https://github.com/lattice/quda/pull/1485/files#diff-38727af1272c2f4e15d727785175dd75e678fd5edc476cf1d66992d4960382b7> (1)
  *   M tests/staggered_eigensolve_test_gtest.hpp<https://github.com/lattice/quda/pull/1485/files#diff-f3931e42a3ceb9e7422ad9c94eac8ecaa9ad74dca3e3c2e6b1897c737ff39898> (7)

Patch Links:

  *   https://github.com/lattice/quda/pull/1485.patch
  *   https://github.com/lattice/quda/pull/1485.diff

**Comment by maddyscientist** [comment]
Thanks @stevengottlieb for testing this.  This is indeed an Arm issue, with NEON being one of the vector instruction sets equivalent to SEE on Intel.  Moreover, I see the issue is with compiling the Eigen headers.  I'll investigate and report back.

**Comment by stevengottlieb** [comment]
Thanks, Kate!  I appreciate your help.

On Aug 14, 2024, at 1:30 PM, maddyscientist ***@***.***> wrote:



Thanks @stevengottlieb<https://github.com/stevengottlieb> for testing this. This is indeed an Arm issue, with NEON being one of the vector instruction sets equivalent to SEE on Intel. Moreover, I see the issue is with compiling the Eigen headers. I'll investigate and report back.

**Comment by maddyscientist** [comment]
@stevengottlieb this is a bug in Eigen it seems.  The patch to apply is to replace 
```
#if EIGEN_COMP_CLANG || EIGEN_COMP_CASTXML
```
with
```
#if EIGEN_COMP_CLANG || EIGEN_COMP_CASTXML || __NVCOMPILER_LLVM__
```
in `$PATH_TO_QUDA_BUILD_DIR/_deps/eigen-src/Eigen/src/Core/arch/NEON/Complex.h`.  Can you verify this fixes the issue for you?

I'm trying to work out the best way to fix this issue in the short term (until Eigen is fixed at source).

**Comment by stevengottlieb** [comment]
@maddyscientist Thanks, Kate.

I found two such lines the the Complex.h file and applied the fix to both.  I then returned to the build directory and typed
make -j 32
Everything seems fine now.

Thanks again!
Steve

On Aug 14, 2024, at 2:59 PM, maddyscientist ***@***.***> wrote:



@stevengottlieb<https://github.com/stevengottlieb> this is a bug in Eigen it seems. The patch to apply is to replace

#if EIGEN_COMP_CLANG || EIGEN_COMP_CASTXML


with

#if EIGEN_COMP_CLANG || EIGEN_COMP_CASTXML || __NVCOMPILER_LLVM__


in $PATH_TO_QUDA_BUILD_DIR/_deps/eigen-src/Eigen/src/Core/arch/NEON/Complex.h. Can you verify this fixes the issue for you?

I'm trying to work out the best way to fix this issue in the short term (until Eigen is fixed at source).

**Comment by maddyscientist** [comment]
Thanks for confirming the fix works @stevengottlieb.  I've updated the build system to now apply the patch automatically if using the NVHPC compiler, so this should now work out of the box for you.

**Comment by maddyscientist** [comment]
cscs-ci run

**Comment by maddyscientist** [comment]
cscs-ci run

**Comment by stevengottlieb** [comment]
Thanks @maddyscientist.  I started a fresh compile yesterday on Vista and noticed that the build completed without my having to edit the Complex.h.  I was wondering how that came about.

On Aug 18, 2024, at 1:24 PM, maddyscientist ***@***.***> wrote:



Thanks for confirming the fix works @stevengottlieb<https://github.com/stevengottlieb>. I've updated the build system to now apply the patch automatically if using the NVHPC compiler, so this should now work out of the box for you.

**Comment by maddyscientist** [comment]
cscs-ci run

**Comment by maddyscientist** [comment]
cscs-ci run

**Comment by SaltyChiang** [comment]
This happens again in https://github.com/lattice/quda/blob/develop/tests/host_reference/domain_wall_dslash_reference.cpp#L6. https://github.com/lattice/quda/blob/develop/tests/utils/index_utils.hpp#L17-L18 introduces `I` as the template arg again.

**Comment by maddyscientist** [comment]
Thanks @SaltyChiang.  I've fixed this in #1540 that should be merged imminently.  Easy fix to simply delete the `complex.h` header inclusion.

**Pull request merged**
