### PR TITLE
Rename variables in cmake

### LINKED ISSUE #420: cleanup build options for cmake
We should mark some options as advanced if they are likely only to be changed by developers and not by users. It is also a good time to change names if desired.

### PR DESCRIPTION
**Pull request by mathiaswagner**
This closes #420.

We can do further renaming or remove options. (Like: Does building all non-Fortran interfaces hurt?)

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/lattice/quda/pull/423" target="_blank">ReviewNinja

**Comment by mathiaswagner** [comment]
ping

**Comment by maddyscientist** [comment]
Sorry I'd forgotten about this pull.  It all looks good, only minor suggestion is to reorder the force build options so that they'll appear together:
```
QUDA_GAUGE_FORCE -> QUDA_FORCE_GAUGE
QUDA_ASQTAD_FORCE -> QUDA_FORCE_ASQTAD
```
etc.

**Comment by mathiaswagner** [comment]
sounds good

**Comment by maddyscientist** [comment]
Looks like we're all good here.  I see the builds only failed because of the C++/C interface issue.  @mathiaswagner, I'm correct in thinking we're all set to merge now?

**Comment by mathiaswagner** [comment]
Yes. It was all just naming.

On 21.01.2016, at 19:49, maddyscientist <notifications@github.com<mailto:notifications@github.com>> wrote:


Looks like we're all good here. I see the builds only failed because of the C++/C interface issue. @mathiaswagner<https://github.com/mathiaswagner>, I'm correct in thinking we're all set to merge now?

-
Reply to this email directly or view it on GitHub<https://github.com/lattice/quda/pull/423#issuecomment-173671666>.

NVIDIA GmbH, Wuerselen, Germany, Amtsgericht Aachen, HRB 8361
Managing Director: Karen Theresa Burns

-----------------------------------------------------------------------------------
This email message is for the sole use of the intended recipient(s) and may contain
confidential information.  Any unauthorized review, use, disclosure or distribution
is prohibited.  If you are not the intended recipient, please contact the sender by
reply email and destroy all copies of the original message.
-----------------------------------------------------------------------------------

**Pull request merged**
