### PR TITLE
Initial HIP Target Skeleton

### PR DESCRIPTION
**Pull request by bjoo**
Miniscule feature branch adding lib/targets/hip directory and some CMake infrastructure to select it.
Actual files in lib/targets/hip are not substantially changed from NVCC ones except
* blas_lapack_cublas.cpp renamed blas_lapack_hipblas.cpp in anticipation
* device.cpp has a printfQuda proclaiming (semi erroneously) that it is in fact now a HIP backend -- as a debugging aid for now.

@cpviolator can tackle the malloc.cpp here and @bjoo can have a go at device as agreed for homework. Adding a DPC++ directory for @jcosborn should be straightforward, but maybe for a later PR.

### CODE REVIEW

**Review by maddyscientist — APPROVED** [review]
Nothing controversial there.  We can merge this I think once the build tests have finished.

**Comment by mathiaswagner** [comment]
As the HIP part won't be compiled by Jenkins: what is the status of getting something in place for that? 

We should also define code owners for the hip target. (I think GitHub has some functionality to do that).  

Apart from that the changes are fine with me.

**Comment by bjoo** [comment]
I have sent a request to learn more about local CI but have not heard back. So I'll send that again. :)
I think for the now, there is no important need to test the hip end under jenkins until it actually does
something -- this is just a placeholder for Dean and I to hang off stuff for now.

Best,
B

===
Balint Joo, Sr Staff Computational Scientist, Scientific Computing Group
Oak Ridge Leadership Computing Facility
Oak Ridge National Laboratory
P.O. Box 2008, 1 Bethel Valley Road, Oak Ridge, TN 37831, USA
email: joob AT ornl.gov.  Tel: +1-757-912-0566 (cell, remote)

________________________________________

**Comment by maddyscientist** [comment]
Ok, build tests have failed, but this can rectified by merging in the latest develop which has the required fixes for clang building.

@bjoo @mathiaswagner since the contents of the hip target directory are currently dummy carbon copies of the cuda variants: for now, why not just make these map directly to the CUDA ones.  E.g., `lib/target/hip/malloc.cpp` could just be 
```c++
#include "../target/cuda/malloc.cpp"
```
at least until something is implemented.  This will ensure that any changes that go into the CUDA files don't have to be pointlessly copied in the HIP files.

**Comment by ybyang** [comment]
A incomplete type/function/enum list used the CUDA API:

using qudaStream_t = cudaStream_t;
using qudaMemcpyKind = cudaMemcpyKind;
using qudaError_t = cudaError_t;
using qudaEvent_t = cudaEvent_t;
using qudaMemoryType = cudaMemoryType;
using qudaIpcMemHandle_t = cudaIpcMemHandle_t;
using qudaDeviceProp = cudaDeviceProp;
#define qudaHostGetDevicePointer cudaHostGetDevicePointer
#define qudaStreamCreate cudaStreamCreate
#define qudaStreamDestroy cudaStreamDestroy
#define qudaEventCreate cudaEventCreate
#define qudaEventCreateWithFlags hipEventCreateWithFlags
#define qudaEventDisableTiming cudaEventDisableTiming
#define qudaEventDestroy cudaEventDestroy
#define qudaEventElapsedTime cudaEventElapsedTime
#define qudaSuccess cudaSuccess
#define qudaErrorNotReady cudaErrorNotReady
#define qudaErrorUnknown cudaErrorUnknown
#define qudaSuccessjit CUDA_SUCCESS
#define qudaEventDestroy cudaEventDestroy
#define qudaGetLastError cudaGetLastError
#define qudaGetErrorString cudaGetErrorString
#define qudaHostRegister cudaHostRegister
#define qudaHostAlloc cudaHostAlloc
#define qudaHostRegisterMapped cudaHostRegisterMapped
#define qudaHostRegisterPortable cudaHostRegisterPortable
#define QUDA_ERROR_INVALID_VALUE CUDA_ERROR_INVALID_VALUE
#define qudaIpcGetMemHandle cudaIpcGetMemHandle
#define qudaIpcMemLazyEnablePeerAccess cudaIpcMemLazyEnablePeerAccess
#define qudaIpcOpenMemHandle cudaIpcOpenMemHandle
#define qudaIpcCloseMemHandle cudaIpcCloseMemHandle
#define qudaIpcEventHandle_t cudaIpcEventHandle_t
#define qudaMemcpyHostToDevice cudaMemcpyHostToDevice
#define qudaMemcpyDeviceToHost cudaMemcpyDeviceToHost
#define qudaMemcpyDeviceToDevice cudaMemcpyDeviceToDevice
#define qudaFuncSetCacheConfig cudaFuncSetCacheConfig
#define qudaFuncCachePreferL1 cudaFuncCachePreferL1
#define qudaGetErrorName cudaGetErrorName
#define qudaMemset2D cudaMemset2D
#define qudaMemset2DAsync cudaMemset2DAsync
#define qudaCtxSynchronize cudaCtxSynchronize
#define qudaMalloc cudaMalloc
#define qudarand curand
#define qudaFree cudaFree

**Pull request merged**
